#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_EditMaterial.cshtml")]
    public partial class _Areas_Admin_Views_Shared__EditMaterial_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMMaterial>
    {
        public _Areas_Admin_Views_Shared__EditMaterial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
  
    var isNew = Model.Id == 0;
    ViewBag.Title = isNew ? "Добавить статью" : "Редактировать статью \"" + Model.Title + "\"";

            
            #line default
            #line hidden
WriteLiteral("\n");

DefineSection("styles", () => {

WriteLiteral("\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 178), Tuple.Create("\"", 248)
, Tuple.Create(Tuple.Create("", 185), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/bootstrap-datetimepicker.min.css")
, 185), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 279), Tuple.Create("\"", 333)
, Tuple.Create(Tuple.Create("", 286), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/lightbox.min.css")
, 286), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\n");

});

WriteLiteral("<h2>");

            
            #line 10 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\n            <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 489), Tuple.Create("\"", 531)
            
            #line 15 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
, Tuple.Create(Tuple.Create("", 498), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "Articles")
            
            #line default
            #line hidden
, 498), false)
);

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
           Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(">Удалить</button>\n            </form>\n        </div>\n    </div>\n");

            
            #line 22 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(" role=\"tablist\"");

WriteLiteral(">\n    <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#info\"");

WriteLiteral(" aria-controls=\"info\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Основные параметры</a></li>\n");

            
            #line 25 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
     if (!isNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#tags-cloud\"");

WriteLiteral(" aria-controls=\"tags-cloud\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Облако тегов</a></li>\n");

WriteLiteral("        <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#seo\"");

WriteLiteral(" aria-controls=\"seo\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Продвижение</a></li>\n");

WriteLiteral("        <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#mm-videos\"");

WriteLiteral(" aria-controls=\"mm-videos\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Видео</a></li>\n");

WriteLiteral("        <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#mm-pictures\"");

WriteLiteral(" aria-controls=\"mm-pictures\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Фото</a></li>\n");

            
            #line 31 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\n<br />\n<div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\n    <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"info\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\n            Основные параметры материала\n        </div>\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
   Write(Html.EditorForModel(additionalViewData: new { IsNew = isNew }));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n");

            
            #line 41 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
    
            
            #line default
            #line hidden
            
            #line 41 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
     if (!isNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"tags-cloud\"");

WriteLiteral(">\n");

            
            #line 44 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
             using (Ajax.BeginForm("Edit", new { controller = "MaterialTags" }, new AjaxOptions { HttpMethod = "post", UpdateTargetId = "grid-material-tags", OnSuccess = "$('#material-tags-form input[name=\"Title\"]').val('')" }, new { @autocomplete = "off", @id = "material-tags-form" }))
            {
                
            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"MaterialId\"");

WriteLiteral(" name=\"MaterialId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2227), Tuple.Create("\"", 2244)
            
            #line 47 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
, Tuple.Create(Tuple.Create("", 2235), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 2235), false)
);

WriteLiteral(" />\n");

WriteLiteral("                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ModelCoreType\"");

WriteLiteral(" name=\"ModelCoreType\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2325), Tuple.Create("\"", 2353)
            
            #line 48 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
    , Tuple.Create(Tuple.Create("", 2333), Tuple.Create<System.Object, System.Int32>(Model.ModelCoreType
            
            #line default
            #line hidden
, 2333), false)
);

WriteLiteral(" />\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\n                    <p>В данном разделе Вы можете задать теги облака тегов мате" +
"риала</p>\n                </div>\n");

WriteLiteral("                <label");

WriteLiteral(" for=\"Title\"");

WriteLiteral(">Новый тег облака</label> ");

WriteLiteral("<span");

WriteLiteral(" class=\"text-info\"");

WriteLiteral(">(максимально 100 знаков включая пробелы)</span>\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Title\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Введите значение тега\"");

WriteLiteral(" />\n                    <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\n                        <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Добавить</button>\n                    </span>\n                </div>\n");

            
            #line 59 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <br />\n            <div");

WriteLiteral(" id=\"grid-material-tags\"");

WriteLiteral("></div>\n            <br />\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n                <a");

WriteLiteral(" href=\"#info\"");

WriteLiteral(" aria-controls=\"info\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"$(\'a[href=&quot;#info&quot;]\').tab(\'show\'); return false;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-long-arrow-left\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>&nbsp;Параметры</a>\n            </div>\n        </div>\n");

            
            #line 67 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"seo\"");

WriteLiteral(">\n            <h4>SEO параметры материала</h4>\n            <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\n                <p>В данном разделе Вы можете задать SEO параметры материала</p" +
">\n            </div>\n            <div");

WriteLiteral(" id=\"seo-block\"");

WriteLiteral("></div>\n        </div>\n");

            
            #line 75 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"mm-videos\"");

WriteLiteral(">\n            <h4>Видео контент материала</h4>\n            <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\n                <p>В данном разделе Вы можете добавить видео для материала</p>\n" +
"            </div>\n            <div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">\n                <p><b>Внимание!</b> В теле материала можно использовать только " +
"видео, привязанные в данном разделе</p>\n            </div>\n");

WriteLiteral("            ");

            
            #line 84 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
       Write(Html.Partial("_NotMaterialVideos", Model));

            
            #line default
            #line hidden
WriteLiteral("\n            <div");

WriteLiteral(" id=\"videos\"");

WriteLiteral("></div>\n            <br />\n            <a");

WriteLiteral(" href=\"#info\"");

WriteLiteral(" aria-controls=\"info\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"$(\'a[href=&quot;#info&quot;]\').tab(\'show\'); return false;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-long-arrow-left\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>&nbsp;Параметры</a>\n        </div>\n");

            
            #line 89 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"mm-pictures\"");

WriteLiteral(">\n            <h4>Фото контент материала</h4>\n            <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\n                <p>В данном разделе Вы можете добавить фото для материала</p>\n " +
"           </div>\n            <div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">\n                <p><b>Внимание!</b> В теле материала можно использовать только " +
"фото, привязанные в данном разделе</p>\n            </div>\n");

WriteLiteral("            ");

            
            #line 98 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
       Write(Html.Partial("_NotMaterialPictures", Model));

            
            #line default
            #line hidden
WriteLiteral("\n            <div");

WriteLiteral(" id=\"pictures\"");

WriteLiteral("></div>\n            <br />\n            <a");

WriteLiteral(" href=\"#info\"");

WriteLiteral(" aria-controls=\"info\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"$(\'a[href=&quot;#info&quot;]\').tab(\'show\'); return false;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-long-arrow-left\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>&nbsp;Параметры</a>\n        </div>\n");

            
            #line 103 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5279), Tuple.Create("\"", 5324)
, Tuple.Create(Tuple.Create("", 5285), Tuple.Create<System.Object, System.Int32>(Href("~/bower_components/ckeditor/ckeditor.js")
, 5285), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5347), Tuple.Create("\"", 5409)
, Tuple.Create(Tuple.Create("", 5353), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/moment-with-locales.min.js")
, 5353), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5432), Tuple.Create("\"", 5499)
, Tuple.Create(Tuple.Create("", 5438), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/bootstrap-datetimepicker.min.js")
, 5438), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5522), Tuple.Create("\"", 5573)
, Tuple.Create(Tuple.Create("", 5528), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/lightbox.min.js")
, 5528), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5596), Tuple.Create("\"", 5654)
, Tuple.Create(Tuple.Create("", 5602), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 5602), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5677), Tuple.Create("\"", 5747)
, Tuple.Create(Tuple.Create("", 5683), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 5683), false)
);

WriteLiteral(@"></script>
    <script>
        if (CKEDITOR.instances['Html']) {
            CKEDITOR.remove(CKEDITOR.instances['Html']);
        }
        CKEDITOR.replace('Html', { height: 300 });

        $(function () {
            $('#CategoryId, #FrontPictureId').sx_gvl();

            $('#DateOfPublication').closest('.date').datetimepicker({
                locale: 'ru',
                format: 'DD.MM.YYYY HH:mm',
                icons: {
                    time: 'fa fa-clock-o',
                    date: 'fa fa-calendar',
                    up: 'fa fa-arrow-up',
                    down: 'fa fa-arrow-down',
                    previous: 'fa fa-arrow-left',
                    next: 'fa fa-arrow-right',
                    today: '',
                    clear: '',
                    close: ''
                }
            });

            $('#videos, #pictures, #not-mat-videos, #not-mat-pictures').sx_gv();

            //tags cloud
            $('#tags-cloud').on('submit', '#material-tags-form', function(){
                $input=$(this).find('input[name=""Title""]');
                if($input.val()=='')
                    return false;
            });

            $('a[href=""#tags-cloud""]').on('show.bs.tab', function (e) {
                $a = $(e.target);

                $.ajax({
                    method: 'get',
                    url: '");

            
            #line 151 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("Index","MaterialTags"));

            
            #line default
            #line hidden
WriteLiteral("\',\n                    data: {mid:");

            
            #line 152 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                          Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(", mct: \'");

            
            #line 152 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                           Write(Model.ModelCoreType);

            
            #line default
            #line hidden
WriteLiteral(@"'},
                    beforeSend:function(){
                        $('a[role=""tab""]').find('.tab-spinner').remove();
                        $a.prepend('<i class=""fa fa-spinner fa-spin tab-spinner""></i>');
                    },
                    success: function (result) {
                        $('#grid-material-tags').html(result);
                        $('#grid-material-tags').sx_gv();
                    },
                    complete:function(){
                        $a.find('.tab-spinner').remove();
                    }
                });
            })

            //seo
            $('a[href=""#seo""]').on('show.bs.tab', function (e) {
                $a = $(e.target);

                $.ajax({
                    method: 'get',
                    url: '");

            
            #line 173 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("EditForMaterial", "SeoTags"));

            
            #line default
            #line hidden
WriteLiteral("\',\n                    data: {mid:");

            
            #line 174 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                          Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(", mct: \'");

            
            #line 174 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                           Write(Model.ModelCoreType);

            
            #line default
            #line hidden
WriteLiteral(@"'},
                    beforeSend:function(){
                        $('a[role=""tab""]').find('.tab-spinner').remove();
                        $a.prepend('<i class=""fa fa-spinner fa-spin tab-spinner""></i>');
                    },
                    success: function (result) {
                        $('#seo-block').html(result);
                        $('#seo-kw').sx_gv();
                    },
                    complete:function(){
                        $a.find('.tab-spinner').remove();
                    }
                });
            })

            //videos
            $('a[href=""#mm-videos""]').on('show.bs.tab', function (e) {
                $a = $(e.target);

                $.ajax({
                    method: 'get',
                    url: '");

            
            #line 195 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("Index", "VideoLinks"));

            
            #line default
            #line hidden
WriteLiteral("\',\n                    data: {mid:");

            
            #line 196 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                          Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(", mct: \'");

            
            #line 196 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                           Write(Model.ModelCoreType);

            
            #line default
            #line hidden
WriteLiteral(@"'},
                    beforeSend:function(){
                        $('a[role=""tab""]').find('.tab-spinner').remove();
                        $a.prepend('<i class=""fa fa-spinner fa-spin tab-spinner""></i>');
                    },
                    success: function (result) {
                        $('#videos').html(result);
                    },
                    complete:function(){
                        $a.find('.tab-spinner').remove();
                    }
                });
            })

            $('#videos').on('click', '.sx-gv__create-btn', function(){
                $('#not-mat-videos').modal('show');
                return false;
            });

            $('#not-mat-videos').on('show.bs.modal', function (event) {
                $modal = $(this);
                $.ajax({
                    method: 'get',
                    url: '");

            
            #line 219 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("IndexNotLinked", "VideoLinks"));

            
            #line default
            #line hidden
WriteLiteral("\',\n                    data:{mid:");

            
            #line 220 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                         Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(", mct:\'");

            
            #line 220 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                         Write(Model.ModelCoreType);

            
            #line default
            #line hidden
WriteLiteral("\', fm:");

            
            #line 220 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                                                   Write(bool.FalseString.ToLower());

            
            #line default
            #line hidden
WriteLiteral(@" },
                    success: function (result) {
                        $modal.find('.modal-body').html(result);
                    }
                });
            })

            $('#not-mat-videos-form').submit(function (e) {
                $form = $(this);
                $target = $('#not-mat-videos');
                $target.find('input[type=""checkbox""]:checked').each(function () {
                    $input = $(this);
                    var id = $input.closest('.sx-gv__row').attr('data-row-id');
                    $('<input type=""hidden"" name=""video"" value=""' + id + '"" />').appendTo($form);
                });

                $.ajax({
                    url: '");

            
            #line 237 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("AddMaterialVideo", "VideoLinks"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    data: $form.serialize(),
                    type: 'post',
                    success: function (data) {
                        $('#videos').html(data);
                        $('#not-mat-videos').modal('hide');
                    },
                    complete: function () {
                        $form.find('input[name=""video""]').remove();
                    }
                });
                e.preventDefault();
            });

            //pictures
            $('a[href=""#mm-pictures""]').on('show.bs.tab', function (e) {
                $a = $(e.target);

                $.ajax({
                    method: 'get',
                    url: '");

            
            #line 257 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("Index", "PictureLinks"));

            
            #line default
            #line hidden
WriteLiteral("\',\n                    data: {mid:");

            
            #line 258 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                          Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(", mct: \'");

            
            #line 258 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                           Write(Model.ModelCoreType);

            
            #line default
            #line hidden
WriteLiteral(@"'},
                    beforeSend:function(){
                        $('a[role=""tab""]').find('.tab-spinner').remove();
                        $a.prepend('<i class=""fa fa-spinner fa-spin tab-spinner""></i>');
                    },
                    success: function (result) {
                        $('#pictures').html(result);
                    },
                    complete:function(){
                        $a.find('.tab-spinner').remove();
                    }
                });
            })

            $('#pictures').on('click', '.sx-gv__create-btn', function(){
                $('#not-mat-pictures').modal('show');
                return false;
            });

            $('#not-mat-pictures').on('show.bs.modal', function (event) {
                $modal = $(this);
                $.ajax({
                    method: 'get',
                    url: '");

            
            #line 281 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("IndexNotLinked", "PictureLinks"));

            
            #line default
            #line hidden
WriteLiteral("\',\n                    data:{mid:");

            
            #line 282 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                         Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(", mct:\'");

            
            #line 282 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                         Write(Model.ModelCoreType);

            
            #line default
            #line hidden
WriteLiteral("\', fm:");

            
            #line 282 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                                                                   Write(bool.FalseString.ToLower());

            
            #line default
            #line hidden
WriteLiteral(@" },
                    success: function (result) {
                        $modal.find('.modal-body').html(result);
                    }
                });
            })

            $('#not-mat-pictures-form').submit(function (e) {
                $form = $(this);
                $target = $('#not-mat-pictures');
                $target.find('input[type=""checkbox""]:checked').each(function () {
                    $input = $(this);
                    var id = $input.closest('.sx-gv__row').attr('data-row-id');
                    $('<input type=""hidden"" name=""picture"" value=""' + id + '"" />').appendTo($form);
                });

                $.ajax({
                    url: '");

            
            #line 299 "..\..\Areas\Admin\Views\Shared\_EditMaterial.cshtml"
                     Write(Url.Action("AddMaterialPicture", "PictureLinks"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    data: $form.serialize(),
                    type: 'post',
                    success: function (data) {
                        $('#pictures').html(data);
                        $('#not-mat-pictures').modal('hide');
                    },
                    complete: function () {
                        $form.find('input[name=""picture""]').remove();
                    }
                });
                e.preventDefault();
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
