#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_GridMaterials.cshtml")]
    public partial class _Areas_Admin_Views_Shared__GridMaterials_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMMaterial[]>
    {
        public _Areas_Admin_Views_Shared__GridMaterials_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Shared\_GridMaterials.cshtml"
Write(Html.SxGridView(Model,
    new SxExtantions.SxGridViewSettings<SxVMMaterial>
    {
        Columns = new SxExtantions.SxGridViewColumn<SxVMMaterial>[]{
            new SxExtantions.SxGridViewColumn<SxVMMaterial>{FieldName="DateCreate", Caption="Дата создания"},
            new SxExtantions.SxGridViewColumn<SxVMMaterial>{FieldName="DateOfPublication", Caption="Дата публикации"},
            new SxExtantions.SxGridViewColumn<SxVMMaterial>{FieldName="Title", Caption="Заголовок"},
            new SxExtantions.SxGridViewColumn<SxVMMaterial>{FieldName="SeoTagsId", Caption="Инфо", Template=(m)=> {
                return !m.SeoTagsId.HasValue? "<i class=\"text-warning\" data-toggle=\"tooltip\" title=\"Если не заданы теги для SEO, они установяться программно на основе заголовка и дополнительных метаданных страницы\">не заданы теги seo</i>":null;
            } },
            new SxExtantions.SxGridViewColumn<SxVMMaterial>{FieldName="Show", Caption="Показывать", Template=(m)=> {
                return m.Show? "Да":"Нет";
            } }
        },
        DataAjaxUrl=Url.Action("Index","Articles"),
        EnableCreating=true,
        CreateRowUrl= Url.Action("Edit", "Articles"),
        EnableEditing=true,
        EditRowUrl = x => { return Url.Action("Edit", "Articles", new { id=x.Id }); },
        RowCssClass = x => { return !x.Show ? "warning" : null; },
        ShowPagerInfo=true
    }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
