#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_IndexMaterials.cshtml")]
    public partial class _Areas_Admin_Views_Shared__IndexMaterials_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMMaterial[]>
    {
        public _Areas_Admin_Views_Shared__IndexMaterials_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\_IndexMaterials.cshtml"
  
    ViewBag.Title = "Статьи";

            
            #line default
            #line hidden
WriteLiteral("\n\n<h2>");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\_IndexMaterials.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n<br />\n<div");

WriteLiteral(" id=\"grid\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\_IndexMaterials.cshtml"
Write(Html.Partial("_GridMaterials", Model));

            
            #line default
            #line hidden
WriteLiteral("\n</div>\n\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script>\n        $(\'#grid\').sx_gv();\n    </script>\n");

});

        }
    }
}
#pragma warning restore 1591
