#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Admin_Views_Shared__Layout_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
   
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\n\n<!DOCTYPE html>\n<html");

WriteLiteral(" lang=\"ru\"");

WriteLiteral(">\n<head>\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\n    <title>");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
       Write(ViewBag.Title==null?"admin | leavingrussia.ru":ViewBag.Title+ " | admin | leavingrussia.ru");

            
            #line default
            #line hidden
WriteLiteral("</title>\n\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 348), Tuple.Create("\"", 398)
, Tuple.Create(Tuple.Create("", 355), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/site.min.css")
, 355), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", false));

            
            #line default
            #line hidden
WriteLiteral("\n</head>\n<body>\n    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\n        <nav");

WriteLiteral(" class=\"navbar navbar-default navbar-static-top\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(" style=\"margin-bottom: 0\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                </button>\n                <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1039), Tuple.Create("\"", 1074)
            
            #line 26 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1046), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 1046), false)
);

WriteLiteral(">");

            
            #line 26 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                                                       Write(SX.WebCore.Resources.Settings.adminPanelName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 26 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                                                                                                     Write(SX.WebCore.Resources.Settings.adminPanelVersion);

            
            #line default
            #line hidden
WriteLiteral("</a><br />\n            </div>\n\n            <ul");

WriteLiteral(" class=\"nav navbar-top-links navbar-right\"");

WriteLiteral(">\n                <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\n                    <a");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                        <i");

WriteLiteral(" class=\"fa fa-envelope fa-fw\"");

WriteLiteral("></i>  <i");

WriteLiteral(" class=\"fa fa-caret-down\"");

WriteLiteral("></i>\n                    </a>\n                    <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-messages\"");

WriteLiteral(">\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <stro" +
"ng>John Smith</strong>\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(@">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <stro" +
"ng>John Smith</strong>\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(@">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <stro" +
"ng>John Smith</strong>\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(@">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <strong>Read All Messages</strong>\n            " +
"                    <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral("></i>\n                            </a>\n                        </li>\n            " +
"        </ul>\n                </li>\n                <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\n                    <a");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                        <i");

WriteLiteral(" class=\"fa fa-tasks fa-fw\"");

WriteLiteral("></i>  <i");

WriteLiteral(" class=\"fa fa-caret-down\"");

WriteLiteral("></i>\n                    </a>\n                    <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-tasks\"");

WriteLiteral(">\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <p>\n " +
"                                       <strong>Task 1</strong>\n                 " +
"                       <span");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(">40% Complete</span>\n                                    </p>\n                   " +
"                 <div");

WriteLiteral(" class=\"progress progress-striped active\"");

WriteLiteral(">\n                                        <div");

WriteLiteral(" class=\"progress-bar progress-bar-success\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"40\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 40%\"");

WriteLiteral(">\n                                            <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">40% Complete (success)</span>\n                                        </div>\n   " +
"                                 </div>\n                                </div>\n " +
"                           </a>\n                        </li>\n                  " +
"      <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <p>\n " +
"                                       <strong>Task 2</strong>\n                 " +
"                       <span");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(">20% Complete</span>\n                                    </p>\n                   " +
"                 <div");

WriteLiteral(" class=\"progress progress-striped active\"");

WriteLiteral(">\n                                        <div");

WriteLiteral(" class=\"progress-bar progress-bar-info\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"20\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 20%\"");

WriteLiteral(">\n                                            <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">20% Complete</span>\n                                        </div>\n             " +
"                       </div>\n                                </div>\n           " +
"                 </a>\n                        </li>\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <p>\n " +
"                                       <strong>Task 3</strong>\n                 " +
"                       <span");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(">60% Complete</span>\n                                    </p>\n                   " +
"                 <div");

WriteLiteral(" class=\"progress progress-striped active\"");

WriteLiteral(">\n                                        <div");

WriteLiteral(" class=\"progress-bar progress-bar-warning\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"60\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 60%\"");

WriteLiteral(">\n                                            <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">60% Complete (warning)</span>\n                                        </div>\n   " +
"                                 </div>\n                                </div>\n " +
"                           </a>\n                        </li>\n                  " +
"      <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <p>\n " +
"                                       <strong>Task 4</strong>\n                 " +
"                       <span");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(">80% Complete</span>\n                                    </p>\n                   " +
"                 <div");

WriteLiteral(" class=\"progress progress-striped active\"");

WriteLiteral(">\n                                        <div");

WriteLiteral(" class=\"progress-bar progress-bar-danger\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"80\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 80%\"");

WriteLiteral(">\n                                            <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">80% Complete (danger)</span>\n                                        </div>\n    " +
"                                </div>\n                                </div>\n  " +
"                          </a>\n                        </li>\n                   " +
"     <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <strong>See All Tasks</strong>\n                " +
"                <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral("></i>\n                            </a>\n                        </li>\n            " +
"        </ul>\n                </li>\n                <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\n                    <a");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                        <i");

WriteLiteral(" class=\"fa fa-bell fa-fw\"");

WriteLiteral("></i>  <i");

WriteLiteral(" class=\"fa fa-caret-down\"");

WriteLiteral("></i>\n                    </a>\n                    <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-alerts\"");

WriteLiteral(">\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <i");

WriteLiteral(" class=\"fa fa-comment fa-fw\"");

WriteLiteral("></i> New Comment\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted small\"");

WriteLiteral(">4 minutes ago</span>\n                                </div>\n                    " +
"        </a>\n                        </li>\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <i");

WriteLiteral(" class=\"fa fa-twitter fa-fw\"");

WriteLiteral("></i> 3 New Followers\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted small\"");

WriteLiteral(">12 minutes ago</span>\n                                </div>\n                   " +
"         </a>\n                        </li>\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <i");

WriteLiteral(" class=\"fa fa-envelope fa-fw\"");

WriteLiteral("></i> Message Sent\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted small\"");

WriteLiteral(">4 minutes ago</span>\n                                </div>\n                    " +
"        </a>\n                        </li>\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <i");

WriteLiteral(" class=\"fa fa-tasks fa-fw\"");

WriteLiteral("></i> New Task\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted small\"");

WriteLiteral(">4 minutes ago</span>\n                                </div>\n                    " +
"        </a>\n                        </li>\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <div>\n                                    <i");

WriteLiteral(" class=\"fa fa-upload fa-fw\"");

WriteLiteral("></i> Server Rebooted\n                                    <span");

WriteLiteral(" class=\"pull-right text-muted small\"");

WriteLiteral(">4 minutes ago</span>\n                                </div>\n                    " +
"        </a>\n                        </li>\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <a");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                                <strong>See All Alerts</strong>\n               " +
"                 <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral("></i>\n                            </a>\n                        </li>\n            " +
"        </ul>\n                </li>\n                <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\n                    <a");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\n                        <i");

WriteLiteral(" class=\"fa fa-user fa-fw\"");

WriteLiteral("></i>  <i");

WriteLiteral(" class=\"fa fa-caret-down\"");

WriteLiteral("></i>\n                    </a>\n                    <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-user\"");

WriteLiteral(">\n                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-user fa-fw\"");

WriteLiteral("></i> User Profile</a>\n                        </li>\n                        <li>" +
"\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-gear fa-fw\"");

WriteLiteral("></i> Settings</a>\n                        </li>\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\n                        <li>\n                            <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 11759), Tuple.Create("\"", 11815)
            
            #line 227 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 11768), Tuple.Create<System.Object, System.Int32>(Url.Action("Logoff","Account", new { area=""})
            
            #line default
            #line hidden
, 11768), false)
);

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\n");

WriteLiteral("                                ");

            
            #line 228 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n                            </form>\n                            <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" onclick=\"if(confirm(\'Вы действительно хотите покинуть панель управления?\')){$(th" +
"is).prev(\'form\').submit();}\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-sign-out fa-fw\"");

WriteLiteral("></i> Выйти</a>\n                        </li>\n                    </ul>\n         " +
"       </li>\n            </ul>\n\n            <div");

WriteLiteral(" class=\"navbar-default sidebar\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"sidebar-nav navbar-collapse\"");

WriteLiteral(">\n                    <ul");

WriteLiteral(" class=\"nav\"");

WriteLiteral(" id=\"side-menu\"");

WriteLiteral(">\n                        <li");

WriteLiteral(" class=\"sidebar-search\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"input-group custom-search-form\"");

WriteLiteral(">\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Поиск...\"");

WriteLiteral(">\n                                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\n                                    <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\n                                        <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>\n                                    </button>\n                             " +
"   </span>\n                            </div>\n                        </li>\n    " +
"                    <li>\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13066), Tuple.Create("\"", 13117)
            
            #line 250 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 13073), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home", new { area=""})
            
            #line default
            #line hidden
, 13073), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-home fa-fw\"");

WriteLiteral("></i> На сайт</a>\n                        </li>\n");

            
            #line 252 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 252 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("admin"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-fw fa-user\"");

WriteLiteral("></i> Менеджер пользователей<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n                                    <li>\n                                      " +
"  <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13606), Tuple.Create("\"", 13646)
            
            #line 258 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 13613), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "UserRoles")
            
            #line default
            #line hidden
, 13613), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-fw fa-street-view\"");

WriteLiteral("></i> Роли</a>\n                                    </li>\n                        " +
"            <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13822), Tuple.Create("\"", 13858)
            
            #line 261 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 13829), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Users")
            
            #line default
            #line hidden
, 13829), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-fw fa-user\"");

WriteLiteral("></i> Пользователи</a>\n                                    </li>\n                " +
"                    ");

WriteLiteral("\n                                </ul>\n                            </li>\n");

            
            #line 268 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 269 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("admin"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-history fa-fw\"");

WriteLiteral("></i> Статистика<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n                                    <li>\n                                      " +
"  <a");

WriteAttribute("href", Tuple.Create(" href=\"", 14692), Tuple.Create("\"", 14731)
            
            #line 275 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 14699), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Requests")
            
            #line default
            #line hidden
, 14699), false)
);

WriteLiteral(">Статистика запросов</a>\n                                    </li>\n              " +
"                      <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 14882), Tuple.Create("\"", 14928)
            
            #line 278 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 14889), Tuple.Create<System.Object, System.Int32>(Url.Action("UserLogins", "Statistics")
            
            #line default
            #line hidden
, 14889), false)
);

WriteLiteral(">Статистика входов</a>\n                                    </li>\n                " +
"                </ul>\n                            </li>\n");

            
            #line 282 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 283 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("photo-redactor") || User.IsInRole("video-redactor"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-crop fa-fw\"");

WriteLiteral("></i> Мультимедиа<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n");

            
            #line 288 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 288 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                     if (User.IsInRole("photo-redactor"))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li>\n                                    " +
"        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 15657), Tuple.Create("\"", 15696)
            
            #line 291 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 15664), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Pictures")
            
            #line default
            #line hidden
, 15664), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-image fa-fw\"");

WriteLiteral("></i> Фото-контент</a>\n                                        </li>\n");

            
            #line 293 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");

            
            #line 294 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                     if (User.IsInRole("video-redactor"))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li>\n                                    " +
"        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 16036), Tuple.Create("\"", 16073)
            
            #line 297 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 16043), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Videos")
            
            #line default
            #line hidden
, 16043), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-youtube fa-fw\"");

WriteLiteral("></i> Видео сайта</a>\n                                        </li>\n");

            
            #line 299 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\n                            </li>\n");

            
            #line 302 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 303 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("smm"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-globe fa-fw\"");

WriteLiteral("></i> Соцсети<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n                                    <li>\n                                      " +
"  <a");

WriteAttribute("href", Tuple.Create(" href=\"", 16705), Tuple.Create("\"", 16740)
            
            #line 309 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 16712), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Nets")
            
            #line default
            #line hidden
, 16712), false)
);

WriteLiteral("> Поддерживаемы сети</a>\n                                    </li>\n              " +
"                      <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 16891), Tuple.Create("\"", 16930)
            
            #line 312 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 16898), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "SiteNets")
            
            #line default
            #line hidden
, 16898), false)
);

WriteLiteral("> Сети сайта</a>\n                                    </li>\n                      " +
"              <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 17073), Tuple.Create("\"", 17116)
            
            #line 315 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 17080), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "ShareButtons")
            
            #line default
            #line hidden
, 17080), false)
);

WriteLiteral("> Кнопки шар</a>\n                                    </li>\n                      " +
"          </ul>\n                            </li>\n");

            
            #line 319 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 320 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("author-article") || User.IsInRole("author-news") || User.IsInRole("admin"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-archive fa-fw\"");

WriteLiteral("></i> Материалы<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                            <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n");

            
            #line 325 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 325 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                 if (User.IsInRole("author-article"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\n                                        " +
"<a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-book\"");

WriteLiteral("></i> Статьи <span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                        <ul");

WriteLiteral(" class=\"nav nav-third-level\"");

WriteLiteral(">\n\n                                            <li>\n                             " +
"                   <a");

WriteAttribute("href", Tuple.Create(" href=\"", 18070), Tuple.Create("\"", 18130)
            
            #line 332 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 18077), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { controller = "Articles" })
            
            #line default
            #line hidden
, 18077), false)
);

WriteLiteral(">Каталог статей</a>\n                                            </li>\n\n");

            
            #line 335 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 335 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                             if (User.IsInRole("admin"))
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <li>\n                            " +
"                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 18428), Tuple.Create("\"", 18531)
            
            #line 338 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 18435), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "MaterialCategories", new { mct = SX.WebCore.Enums.ModelCoreType.Article })
            
            #line default
            #line hidden
, 18435), false)
);

WriteLiteral(">Категории статей</a>\n                                                </li>\n");

            
            #line 340 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </ul>\n                                   " +
" </li>\n");

            
            #line 343 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\n                        </li>\n");

            
            #line 346 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 347 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("seo"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-cog fa-fw\"");

WriteLiteral("></i> Seo оптимизация<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n                                    <li>\n                                      " +
"  <a");

WriteAttribute("href", Tuple.Create(" href=\"", 19251), Tuple.Create("\"", 19309)
            
            #line 353 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 19258), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { controller= "SeoTags" })
            
            #line default
            #line hidden
, 19258), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-cogs\"");

WriteLiteral("></i> Метатеги</a>\n                                    </li>\n                    " +
"                <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 19476), Tuple.Create("\"", 19536)
            
            #line 356 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 19483), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { controller= "Redirects" })
            
            #line default
            #line hidden
, 19483), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-arrow-right\"");

WriteLiteral("></i> 301 редирект</a>\n                                    </li>\n                " +
"                    <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 19714), Tuple.Create("\"", 19777)
            
            #line 359 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 19721), Tuple.Create<System.Object, System.Int32>(Url.Action("EditRobotsFile", new { controller= "Seo" })
            
            #line default
            #line hidden
, 19721), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-ship\"");

WriteLiteral("></i> robot.txt</a>\n                                    </li>\n                   " +
"                 <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 19945), Tuple.Create("\"", 20006)
            
            #line 362 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 19952), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", new { controller= "BannedUrls" })
            
            #line default
            #line hidden
, 19952), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-ban\"");

WriteLiteral("></i> Забаненные адреса</a>\n                                    </li>\n           " +
"                     </ul>\n                            </li>\n");

            
            #line 366 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 367 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("admin"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-cube fa-fw\"");

WriteLiteral("></i> Монетизация<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n                                    <li>\n                                      " +
"  <a");

WriteAttribute("href", Tuple.Create(" href=\"", 20580), Tuple.Create("\"", 20618)
            
            #line 373 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 20587), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Banners")
            
            #line default
            #line hidden
, 20587), false)
);

WriteLiteral("> Список баннеров</a>\n                                    </li>\n                 " +
"                   <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 20766), Tuple.Create("\"", 20809)
            
            #line 376 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 20773), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "BannerGroups")
            
            #line default
            #line hidden
, 20773), false)
);

WriteLiteral("> Группы баннеров</a>\n                                    </li>\n                 " +
"                   <li>\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 20957), Tuple.Create("\"", 21002)
            
            #line 379 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 20964), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "AffiliateLinks")
            
            #line default
            #line hidden
, 20964), false)
);

WriteLiteral("> Партнерские ссылки</a>\n                                    </li>\n              " +
"                  </ul>\n                            </li>\n");

            
            #line 383 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 384 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("admin"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-wrench fa-fw\"");

WriteLiteral("></i> Настройки<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                                <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n                                    <li>\n                                      " +
"  <a");

WriteAttribute("href", Tuple.Create(" href=\"", 21552), Tuple.Create("\"", 21598)
            
            #line 390 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 21559), Tuple.Create<System.Object, System.Int32>(Url.Action("EditSite", "SiteSettings")
            
            #line default
            #line hidden
, 21559), false)
);

WriteLiteral(">Настройки сайта</a>\n                                    </li>\n");

            
            #line 392 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 392 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                     if (User.IsInRole("architect"))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li>\n                                    " +
"        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 21860), Tuple.Create("\"", 21896)
            
            #line 395 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 21867), Tuple.Create<System.Object, System.Int32>(Url.Action("GetLog", "Logs")
            
            #line default
            #line hidden
, 21867), false)
);

WriteLiteral("> Скачать лог</a>\n                                        </li>\n");

            
            #line 397 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\n                            </li>\n");

            
            #line 400 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 401 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("admin"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 22243), Tuple.Create("\"", 22281)
            
            #line 404 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 22250), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Valutes")
            
            #line default
            #line hidden
, 22250), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-rub fa-fw\"");

WriteLiteral("></i> Курсы валют ЦБ РФ</a>\n                            </li>\n");

            
            #line 406 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <li>\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-tasks fa-fw\"");

WriteLiteral("></i> FAQ<span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\n                            <ul");

WriteLiteral(" class=\"nav nav-second-level\"");

WriteLiteral(">\n                                <li>\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 22675), Tuple.Create("\"", 22709)
            
            #line 411 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 22682), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "FAQ")
            
            #line default
            #line hidden
, 22682), false)
);

WriteLiteral(">Справка</a>\n                                </li>\n");

            
            #line 413 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 413 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                 if (User.IsInRole("architect"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\n                                        " +
"<a");

WriteAttribute("href", Tuple.Create(" href=\"", 22943), Tuple.Create("\"", 23042)
            
            #line 416 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 22950), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "MaterialCategories", new { mct=SX.WebCore.Enums.ModelCoreType.Manual})
            
            #line default
            #line hidden
, 22950), false)
);

WriteLiteral(">Справочные категории</a>\n                                    </li>\n");

WriteLiteral("                                    <li>\n                                        " +
"<a");

WriteAttribute("href", Tuple.Create(" href=\"", 23194), Tuple.Create("\"", 23232)
            
            #line 419 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 23201), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Manuals")
            
            #line default
            #line hidden
, 23201), false)
);

WriteLiteral(">Справочные материалы</a>\n                                    </li>\n");

            
            #line 421 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <li>\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 23410), Tuple.Create("\"", 23460)
            
            #line 423 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 23417), Tuple.Create<System.Object, System.Int32>(Url.Action("ReleaseNotes", "SiteSettings")
            
            #line default
            #line hidden
, 23417), false)
);

WriteLiteral(">История выпусков</a>\n                                </li>\n                     " +
"       </ul>\n                        </li>\n                        <li>\n        " +
"                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 23644), Tuple.Create("\"", 23679)
            
            #line 428 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 23651), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Chat")
            
            #line default
            #line hidden
, 23651), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa fa-comments-o fa-fw\"");

WriteLiteral("></i> Чат</a>\n                        </li>\n                        <li>\n        " +
"                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 23820), Tuple.Create("\"", 23861)
            
            #line 431 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 23827), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Analizator")
            
            #line default
            #line hidden
, 23827), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-line-chart fa-fw\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i> Анализатор</a>\n                        </li>\n                    </ul>\n    " +
"            </div>\n            </div>\n        </nav>\n\n        <div");

WriteLiteral(" id=\"page-wrapper\"");

WriteLiteral(">\n            <small");

WriteLiteral(" class=\"pull-right text-muted\"");

WriteLiteral(">Последний старт: ");

            
            #line 439 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                                             Write(SX.WebCore.MvcApplication.SxMvcApplication.LastStartDate);

            
            #line default
            #line hidden
WriteLiteral("</small>\n");

WriteLiteral("            ");

            
            #line 440 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n    </div>\n\n    ");

WriteLiteral("\n    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" id=\"modal-error\"");

WriteLiteral(">\n");

            
            #line 446 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 446 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
         using (Ajax.BeginForm("SendErrorToArchitect", new { controller = "Errors" }, new AjaxOptions { HttpMethod = "post", OnBegin= "$('#modal-error-send-btn').append('<i class=\"fa fa-spinner fa-spipn\"></i>')", OnSuccess= "$('#modal-error-send-btn').find('.fa-spinner').remove();$('#modal-error').modal('hide'); alert('Письмо успешно отправлено!')" }, new { @id = "modal-error-form" }))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-content panel-danger\"");

WriteLiteral(">\n                    <div");

WriteLiteral(" class=\"modal-header panel-heading\"");

WriteLiteral(" style=\"border-top-left-radius: inherit; border-top-right-radius: inherit;\"");

WriteLiteral(">\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\n                        <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral("></h4>\n                    </div>\n                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"rawUrl\"");

WriteLiteral(" />\n                        <textarea");

WriteLiteral(" name=\"html\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" style=\"height:300px; resize:none;\"");

WriteLiteral("></textarea>\n                    </div>\n                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                        <ul");

WriteLiteral(" class=\"list-unstyled list-inline\"");

WriteLiteral(">\n                            <li>\n                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"modal-error-send-btn\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-envelope-o\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i> Отправить разработчику</button>\n                            </li>\n         " +
"                   <li>\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Закрыть</button>\n                            </li>\n                        </ul>" +
"\n                    </div>\n                </div>\n            </div>\n");

            
            #line 470 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26177), Tuple.Create("\"", 26224)
, Tuple.Create(Tuple.Create("", 26183), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/site.min.js")
, 26183), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 26247), Tuple.Create("\"", 26301)
, Tuple.Create(Tuple.Create("", 26253), Tuple.Create<System.Object, System.Int32>(Href("~/content/dist/js/jquery.unobtrusive-ajax.min.js")
, 26253), false)
);

WriteLiteral("></script>\n    <script>\n        $(function () {\n            $(\'#side-menu\').metis" +
"Menu();\n\n            $(window).bind(\"load resize\", function () {\n               " +
" topOffset = 50;\n                width = (this.window.innerWidth > 0) ? this.win" +
"dow.innerWidth : this.screen.width;\n                if (width < 768) {\n         " +
"           $(\'div.navbar-collapse\').addClass(\'collapse\');\n                    to" +
"pOffset = 100; // 2-row-menu\n                } else {\n                    $(\'div" +
".navbar-collapse\').removeClass(\'collapse\');\n                }\n\n                h" +
"eight = ((this.window.innerHeight > 0) ? this.window.innerHeight : this.screen.h" +
"eight) - 1;\n                height = height - topOffset;\n                if (hei" +
"ght < 1) height = 1;\n                if (height > topOffset) {\n                 " +
"   $(\"#page-wrapper\").css(\"min-height\", (height) + \"px\");\n                }\n    " +
"        });\n\n            var url = window.location;\n            var element = $(" +
"\'ul.nav a\').filter(function () {\n                return this.href == url || url." +
"href.indexOf(this.href) == 0;\n            }).addClass(\'active\').parent().parent(" +
").addClass(\'in\').parent();\n            if (element.is(\'li\')) {\n                e" +
"lement.addClass(\'active\');\n            }\n\n            $(document).ajaxError(func" +
"tion (event, xhr, settings) {\n                $modal = $(\'#modal-error\');\n      " +
"          $modal.find(\'.modal-header h4\').html(\'<span class=\"text-danger\">Ошибка" +
" \' + xhr.status+ \'</span>\');\n                $modal.find(\'.modal-body textarea\')" +
".val(xhr.responseText);\n                $modal.find(\'.modal-body input[name=\"raw" +
"Url\"]\').val(\'");

            
            #line 509 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
                                                                Write(Request.RawUrl);

            
            #line default
            #line hidden
WriteLiteral(@"');
                $('.modal').modal('hide');
                $('#modal-error').modal('show');
            });

            $().alert();

            $('[data-toggle=""tooltip""]').tooltip();

            $(document).mouseup(function (e) {
                var container = $("".sx-gvl__dropdown"");

                if (!container.is(e.target) && container.has(e.target).length === 0) {
                    container.hide();
                }
            });
        });
    </script>
");

WriteLiteral("    ");

            
            #line 527 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\n</body>\n</html>\n");

        }
    }
}
#pragma warning restore 1591
