#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_NotMaterialPictures.cshtml")]
    public partial class _Areas_Admin_Views_Shared__NotMaterialPictures_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMMaterial>
    {
        public _Areas_Admin_Views_Shared__NotMaterialPictures_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"not-mat-pictures\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\_NotMaterialPictures.cshtml"
                                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                <p><small>Непривязанные фото</small></p>\r\n            </di" +
"v>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" id=\"grid-not-mat-videos\"");

WriteLiteral(">\r\n\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"list-unstyled list-inline\"");

WriteLiteral(">\r\n                    <li>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Закрыть</button>\r\n                    </li>\r\n                    <li>\r\n         " +
"               <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 908), Tuple.Create("\"", 966)
            
            #line 20 "..\..\Areas\Admin\Views\Shared\_NotMaterialPictures.cshtml"
, Tuple.Create(Tuple.Create("", 917), Tuple.Create<System.Object, System.Int32>(Url.Action("AddMaterialPicture", "PictureLinks")
            
            #line default
            #line hidden
, 917), false)
);

WriteLiteral(" id=\"not-mat-pictures-form\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 21 "..\..\Areas\Admin\Views\Shared\_NotMaterialPictures.cshtml"
                       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"mid\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1110), Tuple.Create("\"", 1127)
            
            #line 22 "..\..\Areas\Admin\Views\Shared\_NotMaterialPictures.cshtml"
, Tuple.Create(Tuple.Create("", 1118), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 1118), false)
);

WriteLiteral(" />\r\n                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"mct\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1192), Tuple.Create("\"", 1220)
            
            #line 23 "..\..\Areas\Admin\Views\Shared\_NotMaterialPictures.cshtml"
, Tuple.Create(Tuple.Create("", 1200), Tuple.Create<System.Object, System.Int32>(Model.ModelCoreType
            
            #line default
            #line hidden
, 1200), false)
);

WriteLiteral(" />\r\n                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Добавить</button>\r\n                        </form>\r\n                    </li>\r\n " +
"               </ul>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
