#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Banners/_FindGridView.cshtml")]
    public partial class _Areas_Admin_Views_Banners__FindGridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMBanner[]>
    {
        public _Areas_Admin_Views_Banners__FindGridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Banners\_FindGridView.cshtml"
  
    var pagerInfo = ViewBag.PagerInfo;
    var filter = ViewBag.Filter != null ? (SxVMBanner)ViewBag.Filter : null;
    var sortDirections = ViewBag.Order != null ? (Dictionary<string, SxExtantions.SortDirection>)ViewBag.Order : null;
    var bannerGroupId = (Guid)ViewBag.BannerGroupId;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Banners\_FindGridView.cshtml"
Write(Html.SxGridView(
        new SxExtantions.SxGridViewSettings<SxVMBanner>
        {
            UpdateTargetId = "grid-banners",
            Data = Model,
            Columns = new SxExtantions.SxGridViewColumn<SxVMBanner>[]{
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="Id", Caption="Идентификатор"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="Url", Caption="Адрес перехода"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="Title", Caption="Заголовок"}
            },
            PagerInfo = pagerInfo,
            Filter = filter,
            SortDirections = sortDirections,
            EnableCreate = false,
            EnableEditing = false,
            Mode = SxExtantions.SxGridViewMode.Lookup,
            FuncGetId =(b)=>b.Id,
            FuncTextField=()=>"Id",
            FuncDataUrl=()=>Url.Action(MVC.Banners.FindGridView(bgid: bannerGroupId))
        },
            new { @class = "table table-condensed table-bordered table-responsive table-striped" }
    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
