#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Banners/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_Banners__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMBanner[]>
    {
        public _Areas_Admin_Views_Banners__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Banners\_GridView.cshtml"
Write(Html.SxGridView(Model,
        new SxExtantions.SxGridViewSettings<SxVMBanner>
        {
            Columns = new SxExtantions.SxGridViewColumn<SxVMBanner>[]{
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="Id", Caption="Идентификатор"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="Url", Caption="Адрес перехода"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="Title", Caption="Заголовок"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="Place", Caption="Позиция", Template=(b)=> {
                    return b.Place==SX.WebCore.SxBanner.BannerPlace.Unknown? null : string.Format("<b class=\"text-warning\">{0}</b>", b.Place);
                } },
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="ShowsCount", Caption="Показов"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="ClicksCount", Caption="Кликов"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="CTR", Caption="CTR, %"},
                new SxExtantions.SxGridViewColumn<SxVMBanner>{FieldName="PictureId", Caption="Картинка", Template=(p)=> {
                return string.Format("<a data-lightbox=\"roadtrip\" data-title=\"{1}\" data-toggle=\"tooltip\" title=\"Помотреть картинку\" href=\"/pictures/picture/{0}\"><i class=\"fa fa-picture-o\"></i></a>", p.PictureId, p.Title);
            }, ColumnCssClass=x=> { return "col-cm"; }
                }
            },
            EnableCreating = true,
            CreateRowUrl = Url.Action("Edit","Banners"),
            EnableEditing = true,
            EditRowUrl = x => { return Url.Action("Edit", "Banners", new { id=x.Id}); },
            DataAjaxUrl = Url.Action("Index", "Banners"),
            ShowPagerInfo=true,
            RowCssClass = x => { return !string.IsNullOrEmpty(x.Description) ? null : "warning"; }
        }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
