#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Banners/Edit.cshtml")]
    public partial class _Areas_Admin_Views_Banners_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMBanner>
    {
        public _Areas_Admin_Views_Banners_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
  
    var isNew = Model.Id == Guid.Empty;
    ViewBag.Title = isNew ? "Добавить баннер" : "Редактировать баннер \"" + Model.Title ?? Model.Id.ToString() + "\"";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 216), Tuple.Create("\"", 270)
, Tuple.Create(Tuple.Create("", 223), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/lightbox.min.css")
, 223), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("\r\n<h2>");

            
            #line 11 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 397), Tuple.Create("\"", 437)
            
            #line 15 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 406), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete","Banners")
            
            #line default
            #line hidden
, 406), false)
);

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
       Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" onclick=\"if (!confirm(\'Удалить запись?\')) { return false;}\"");

WriteLiteral(">Удалить</button>\r\n        </form>\r\n    </div>\r\n");

            
            #line 21 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 713), Tuple.Create("\"", 751)
            
            #line 23 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 722), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit","Banners")
            
            #line default
            #line hidden
, 722), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 30 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.LabelFor(x => x.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.EditorFor(x => x.Url, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите адрес ссылки баннера" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.LabelFor(x => x.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите заголовок" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.LabelFor(x => x.PictureId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
                 if (!isNew && Model.Picture != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" style=\"color:inherit; text-decoration:none;\"");

WriteLiteral(" data-lightbox=\"roadtrip\"");

WriteLiteral(" data-title=\"");

            
            #line 47 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
                                                                                                    Write(Model.Picture.Caption);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"right\"");

WriteLiteral(" title=\"Помотреть картинку\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1943), Tuple.Create("\"", 2009)
            
            #line 47 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
                                                                                                                               , Tuple.Create(Tuple.Create("", 1950), Tuple.Create<System.Object, System.Int32>(Url.Action("Picture","Pictures",new { id=Model.PictureId})
            
            #line default
            #line hidden
, 1950), false)
);

WriteLiteral(">&nbsp;<i");

WriteLiteral(" class=\"fa fa-picture-o\"");

WriteLiteral("></i></a>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 49 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.EditorFor(x => x.PictureId, new { htmlAttributes = new { @class = "form-control", @placeholder = "Укажите изображение" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.PictureId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 56 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
   Write(Html.LabelFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 57 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
   Write(Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите описание" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 58 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <h4>Парметры сквозных баннеров</h4>\r\n    <p");

WriteLiteral(" class=\"text-info\"");

WriteLiteral(" style=\"max-width:400px;\"");

WriteLiteral(">Баннер будет отображаться как сквозной только при условии задания этих парметров" +
". Но даже если параметры заданы, баннер все равно может использоваться как обычн" +
"ый</p>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 67 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.LabelFor(x => x.Place));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <a");

WriteLiteral(" style=\"color:inherit; text-decoration:none;\"");

WriteLiteral(" data-lightbox=\"cheme\"");

WriteLiteral(" data-title=\"Схема шаблона\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"right\"");

WriteLiteral(" title=\"Помотреть схему\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3195), Tuple.Create("\"", 3230)
, Tuple.Create(Tuple.Create("", 3202), Tuple.Create<System.Object, System.Int32>(Href("~/Content/i/bannerPlaces.jpg")
, 3202), false)
);

WriteLiteral(">&nbsp;<i");

WriteLiteral(" class=\"fa fa-question-circle-o\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("                ");

            
            #line 69 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.EnumDropDownListFor(x => x.Place, new { @class = "form-control", @placeholder = "Задайте место баннера на странице" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 70 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.Place));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 75 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.LabelFor(x => x.RawUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.EditorFor(x => x.RawUrl, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите внутренний адрес страницы" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 77 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.RawUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 83 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
                                                  Write(isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4043), Tuple.Create("\"", 4080)
            
            #line 84 "..\..\Areas\Admin\Views\Banners\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4050), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Banners")
            
            #line default
            #line hidden
, 4050), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Назад</a>\r\n    </div>\r\n</form>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4193), Tuple.Create("\"", 4238)
, Tuple.Create(Tuple.Create("", 4199), Tuple.Create<System.Object, System.Int32>(Href("~/bower_components/ckeditor/ckeditor.js")
, 4199), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4262), Tuple.Create("\"", 4313)
, Tuple.Create(Tuple.Create("", 4268), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/lightbox.min.js")
, 4268), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4337), Tuple.Create("\"", 4395)
, Tuple.Create(Tuple.Create("", 4343), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 4343), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4419), Tuple.Create("\"", 4489)
, Tuple.Create(Tuple.Create("", 4425), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 4425), false)
);

WriteLiteral(@"></script>
    <script>
        if (CKEDITOR.instances['Description']) {
            CKEDITOR.remove(CKEDITOR.instances['Description']);
        }
        CKEDITOR.replace('Description', { height: 300 });

        $(function () {
            $('#PictureId').sx_gvl();
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
