#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Banners/Index.cshtml")]
    public partial class _Areas_Admin_Views_Banners_Index_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMBanner[]>
    {
        public _Areas_Admin_Views_Banners_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Banners\Index.cshtml"
  
    ViewBag.Title = "Баннеры";
    var showsCount = (int)ViewBag.ShowsCount;
    var clicksCount = (int)ViewBag.ClicksCount;
    var ctr = showsCount == 0 ? 0 : Math.Round((decimal)clicksCount * 100 / showsCount, 2);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 278), Tuple.Create("\"", 332)
, Tuple.Create(Tuple.Create("", 285), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/lightbox.min.css")
, 285), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("\r\n<h2>");

            
            #line 13 "..\..\Areas\Admin\Views\Banners\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<br />\r\n<table");

WriteLiteral(" class=\"table table-condensed table-bordered table-responsive table-striped\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th>Всго показов</th>\r\n            <th>" +
"Всего кликов</th>\r\n            <th>Общий CTR, %</th>\r\n        </tr>\r\n    </thead" +
">\r\n    <tbody>\r\n        <tr>\r\n            <td>");

            
            #line 25 "..\..\Areas\Admin\Views\Banners\Index.cshtml"
           Write(showsCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 26 "..\..\Areas\Admin\Views\Banners\Index.cshtml"
           Write(clicksCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td>");

            
            #line 27 "..\..\Areas\Admin\Views\Banners\Index.cshtml"
           Write(ctr);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n\r\n<div");

WriteLiteral(" id=\"grid-banners\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 33 "..\..\Areas\Admin\Views\Banners\Index.cshtml"
Write(Html.Partial("_GridView", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 907), Tuple.Create("\"", 958)
, Tuple.Create(Tuple.Create("", 913), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/lightbox.min.js")
, 913), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\'#grid-banners\')" +
".sx_gv();\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
