#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/MaterialCategories/_TreeViewEditable.cshtml")]
    public partial class _Areas_Admin_Views_MaterialCategories__TreeViewEditable_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMMaterialCategory[]>
    {
        public _Areas_Admin_Views_MaterialCategories__TreeViewEditable_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\MaterialCategories\_TreeViewEditable.cshtml"
  
    int maxLevel = ViewBag.MaxTreeViewLevel;
    SX.WebCore.Enums.ModelCoreType mct = ViewBag.ModelCoreType;

            
            #line default
            #line hidden
WriteLiteral("\n\n");

            
            #line 7 "..\..\Areas\Admin\Views\MaterialCategories\_TreeViewEditable.cshtml"
Write(Html.SxTreeView(
    data: Model,
    settings: new SxExtantions.SxTreeViewTreeViewSettings<SxVMMaterialCategory>
    {
        FuncChildren = x => x.ChildCategories,
        FuncContent = x => x.Title,
        FuncCreateUrl = () => Url.Action("Edit", "MaterialCategories", new { mct=mct }),
        FuncCurLevel = x => x.Level,
        FuncEditUrl = x => Url.Action("Edit", "MaterialCategories", new { mct = x.ModelCoreType, id=x.Id }),
        FuncEditSubNodeUrl = x => Url.Action("Edit", "MaterialCategories", new { mct = mct, pcid = x.Id }),
        MaxLevel = maxLevel,
        FuncSearchUrl = () => Url.Action("Index", "MaterialCategories"),
        UpdateTargetId = "matcat-tv",
        EnableEditing = true,
        EnableFiltering = true
    },
    htmlAttributes: new { @class = "sx-tv table table-condensed table-bordered table-responsive" }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
