#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/MaterialCategories/Edit.cshtml")]
    public partial class _Areas_Admin_Views_MaterialCategories_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMMaterialCategory>
    {
        public _Areas_Admin_Views_MaterialCategories_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
  
    var isNew = Model.Id == null;
    ViewBag.Title = isNew ? "Добавить категорию" : "Редактировать категорию \"" + Model.Title + "\"";
    var forAphorism = Model.ModelCoreType == SX.WebCore.Enums.ModelCoreType.Aphorism;

            
            #line default
            #line hidden
WriteLiteral("\n\n");

DefineSection("styles", () => {

WriteLiteral("\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 282), Tuple.Create("\"", 336)
, Tuple.Create(Tuple.Create("", 289), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/lightbox.min.css")
, 289), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\n");

});

WriteLiteral("\n<h2>");

            
            #line 12 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\n");

            
            #line 14 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\n            <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 494), Tuple.Create("\"", 546)
            
            #line 18 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 503), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "MaterialCategories")
            
            #line default
            #line hidden
, 503), false)
);

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
           Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
           Write(Html.HiddenFor(x => x.ModelCoreType));

            
            #line default
            #line hidden
WriteLiteral("\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" onclick=\"if (!confirm(\'Удалить запись?\')) return false;\"");

WriteLiteral(">Удалить</button>\n            </form>\n        </div>\n    </div>\n");

            
            #line 26 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 890), Tuple.Create("\"", 940)
            
            #line 28 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 899), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "MaterialCategories")
            
            #line default
            #line hidden
, 899), false)
);

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
Write(Html.HiddenFor(x => x.ParentCategoryId));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
Write(Html.HiddenFor(x => x.ModelCoreType));

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 33 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
     if (!isNew && !User.IsInRole("architect"))
    {
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
   Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
                                  
    }

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 38 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
     if (!isNew && User.IsInRole("architect"))
    {

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"OldId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1269), Tuple.Create("\"", 1286)
            
            #line 40 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1277), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 1277), false)
);

WriteLiteral(" />\n");

            
            #line 41 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
       Write(Html.LabelFor(x => x.Id, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n            <span");

WriteLiteral(" class=\"text-info\"");

WriteLiteral("> (не должен содержать кириллицы и любых знаков, кроме тире)</span>\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
       Write(Html.EditorFor(x => x.Id, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите идентификатор категории" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("            ");

            
            #line 46 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
       Write(Html.ValidationMessageFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\n        </div>\n");

            
            #line 48 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 51 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
   Write(Html.LabelFor(x => x.Title, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 52 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
   Write(Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите название категории" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 53 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Title));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\n        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2055), Tuple.Create("\"", 2089)
, Tuple.Create(Tuple.Create("", 2063), Tuple.Create("col-md-", 2063), true)
            
            #line 57 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2070), Tuple.Create<System.Object, System.Int32>(forAphorism?6:12
            
            #line default
            #line hidden
, 2070), false)
);

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 59 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
           Write(Html.LabelFor(x => x.FrontPictureId, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 60 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
                 if (Model.FrontPictureId.HasValue)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" data-original-title=\"Помотреть картинку\"");

WriteLiteral(" onclick=\"x()\"");

WriteLiteral(" data-lightbox=\"roadtrip\"");

WriteLiteral(" data-title=\"Иконка ");

            
            #line 62 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
                                                                                                                     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" title=\"\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2453), Tuple.Create("\"", 2499)
, Tuple.Create(Tuple.Create("", 2460), Tuple.Create("/pictures/picture/", 2460), true)
            
            #line 62 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 2478), Tuple.Create<System.Object, System.Int32>(Model.FrontPictureId
            
            #line default
            #line hidden
, 2478), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-picture-o\"");

WriteLiteral("></i></a>\n");

            
            #line 63 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 64 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
           Write(Html.EditorFor(x => x.FrontPictureId, new { htmlAttributes = new { @class = "form-control", @placeholder = "Выберите изображение" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 65 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.FrontPictureId));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n    </div>\n\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 71 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
                                                  Write(isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\n");

WriteLiteral("        ");

            
            #line 72 "..\..\Areas\Admin\Views\MaterialCategories\Edit.cshtml"
   Write(Html.ActionLink("Назад", "Index", "MaterialCategories", new { mct = Model.ModelCoreType }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n</form>\n\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3132), Tuple.Create("\"", 3183)
, Tuple.Create(Tuple.Create("", 3138), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/lightbox.min.js")
, 3138), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3206), Tuple.Create("\"", 3264)
, Tuple.Create(Tuple.Create("", 3212), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 3212), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3287), Tuple.Create("\"", 3357)
, Tuple.Create(Tuple.Create("", 3293), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 3293), false)
);

WriteLiteral("></script>\n    <script>\n        $(function () {\n            $(\'#FrontPictureId, #" +
"GameId\').sx_gvl();\n        });\n    </script>\n");

});

        }
    }
}
#pragma warning restore 1591
