#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/MaterialCategories/Index.cshtml")]
    public partial class _Areas_Admin_Views_MaterialCategories_Index_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMMaterialCategory[]>
    {
        public _Areas_Admin_Views_MaterialCategories_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\MaterialCategories\Index.cshtml"
  
    SX.WebCore.Enums.ModelCoreType mct = ViewBag.ModelCoreType;
    string title = ViewBag.PageTitle;

            
            #line default
            #line hidden
WriteLiteral("\n\n<h2>");

            
            #line 7 "..\..\Areas\Admin\Views\MaterialCategories\Index.cshtml"
Write(title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n<br />\n\n<div");

WriteLiteral(" id=\"matcat-tv\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Admin\Views\MaterialCategories\Index.cshtml"
Write(Html.Partial("_TreeViewEditable", Model));

            
            #line default
            #line hidden
WriteLiteral("\n</div>\n\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\n        $(function () {\n            $(\'[data-toggle=\"tooltip\"]\').tooltip({\n    " +
"            container: \'body\'\n            });\n        });\n    </script>\n");

});

        }
    }
}
#pragma warning restore 1591
