#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_Users__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAppUser[]>
    {
        public _Areas_Admin_Views_Users__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Users\_GridView.cshtml"
Write(Html.SxGridView(Model, new SxExtantions.SxGridViewSettings<SxVMAppUser>()
{
    Columns = new SxExtantions.SxGridViewColumn<SxVMAppUser>[] {
        new SxExtantions.SxGridViewColumn<SxVMAppUser> { FieldName="NikName", Caption="Ник-нейм"},
        new SxExtantions.SxGridViewColumn<SxVMAppUser> { FieldName="Email", Template=(m)=> {
                return string.Format("<a href=\"mailto:{0}\">{0}</a>", m.Email);
            }},
        new SxExtantions.SxGridViewColumn<SxVMAppUser> { FieldName="IsOnline", Caption="Статус", Template=(u)=> {
                return u.IsOnline?string.Format("<span class=\"badge\">online</span>"):null;
            }, EnableSorting=false}
    },
    EnableEditing = true,
    EditRowUrl = (x) => { return Url.Action("Edit", "Users", new { id = x.Id }); },
    DataAjaxUrl = Url.Action("Index", "Users")
}));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
