#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/_UserReports.cshtml")]
    public partial class _Areas_Admin_Views_Users__UserReports_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<int[]>
    {
        public _Areas_Admin_Views_Users__UserReports_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
  
    var message = ViewBag.UserRoleMessage;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
 if (message != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h3");

WriteLiteral(" class=\"text-warning\"");

WriteLiteral(">Подписки на отчеты <span");

WriteLiteral(" class=\"pull-right small\"");

WriteLiteral(" id=\"mes-user-info\"");

WriteLiteral(">");

            
            #line 8 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
                                                                                             Write(message);

            
            #line default
            #line hidden
WriteLiteral("</span></h3>\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <h3");

WriteLiteral(" class=\"text-warning\"");

WriteLiteral(">Подписки на отчеты</h3>\r\n");

            
            #line 13 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
 using (Ajax.BeginForm("EditUserReport", new { controller="users"}, new AjaxOptions { HttpMethod = "post", UpdateTargetId = "subscription", OnComplete = "removeMessage('#mes-user-info')" }, new { @autocomplete="off"}))
{
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"table table-striped table-condensed\"");

WriteLiteral(">\r\n        <tbody>\r\n            <tr>\r\n                <td");

WriteLiteral(" style=\"width:0;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"reportsId\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" ");

            
            #line 22 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
                                                                  Write(Model.Contains(1)? "checked":null);

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                </td>\r\n                <td>Статистика запросов</td>\r\n       " +
"     </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" style=\"width:0;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"reportsId\"");

WriteLiteral(" value=\"2\"");

WriteLiteral(" ");

            
            #line 28 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
                                                                  Write(Model.Contains(2)? "checked":null);

            
            #line default
            #line hidden
WriteLiteral("  />\r\n                </td>\r\n                <td>Новые материалы</td>\r\n          " +
"  </tr>\r\n            <tr>\r\n                <td");

WriteLiteral(" style=\"width:0;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"reportsId\"");

WriteLiteral(" value=\"3\"");

WriteLiteral(" ");

            
            #line 34 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
                                                                  Write(Model.Contains(3)? "checked":null);

            
            #line default
            #line hidden
WriteLiteral("  />\r\n                </td>\r\n                <td>Баннеры</td>\r\n            </tr>\r" +
"\n        </tbody>\r\n    </table>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Сохранить</button>\r\n        </div>\r\n    </div>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\Users\_UserReports.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
