#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/_UserInfo.cshtml")]
    public partial class _Areas_Admin_Views_Users__UserInfo_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAppUser>
    {
        public _Areas_Admin_Views_Users__UserInfo_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
  
    var message = ViewBag.UserRoleMessage;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
 if (message != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h3");

WriteLiteral(" class=\"text-warning\"");

WriteLiteral(">Общая иформация <span");

WriteLiteral(" class=\"pull-right small\"");

WriteLiteral(" id=\"mes-user-info\"");

WriteLiteral(">");

            
            #line 8 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
                                                                                          Write(message);

            
            #line default
            #line hidden
WriteLiteral("</span></h3>\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <h3");

WriteLiteral(" class=\"text-warning\"");

WriteLiteral(">Общая иформация</h3>\r\n");

            
            #line 13 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
}

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
 using (Ajax.BeginForm("EditUserInfo", new { controller="Users" }, new AjaxOptions { HttpMethod = "post", UpdateTargetId = "info", OnBegin = "$(this).closest('section').find('button[type=\"submit\"]').prepend('<i class=\"fa fa-spin fa-spinner\"></i>&nbsp;')", OnComplete = "removeMessage('#mes-user-info')" }, new { @autocomplete="off"}))
{
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
                              


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.LabelFor(x => x.NikName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.EditorFor(x => x.NikName, new { htmlAttributes = new { @class = "form-control", @placeholder="Введите ник-нейм" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.ValidationMessageFor(x => x.NikName));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.LabelFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите описание" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 28 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.ValidationMessageFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.LabelFor(x => x.AvatarId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.EditorFor(x => x.AvatarId, new { htmlAttributes = new { @class = "form-control", @placeholder = "Выберите аватар" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.ValidationMessageFor(x => x.AvatarId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 36 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.LabelFor(x => x.IsEmployee));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.EditorFor(x => x.IsEmployee, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 40 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"
   Write(Html.ValidationMessageFor(x => x.IsEmployee));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 42 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Сохранить</button>\r\n        </div>\r\n    </div>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Users\_UserInfo.cshtml"

}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
