#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/_UserRoles.cshtml")]
    public partial class _Areas_Admin_Views_Users__UserRoles_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAppUser>
    {
        public _Areas_Admin_Views_Users__UserRoles_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
  
    SxVMAppRole[] roles = ViewBag.Roles;
    var message = ViewBag.UserRoleMessage;
    SxVMAppRole item = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
 if (message != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h3");

WriteLiteral(" class=\"text-warning\"");

WriteLiteral(">Роли <span");

WriteLiteral(" class=\"pull-right small\"");

WriteLiteral(" id=\"mes-roles\"");

WriteLiteral(">");

            
            #line 10 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                                                                           Write(message);

            
            #line default
            #line hidden
WriteLiteral("</span></h3>\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <h3");

WriteLiteral(" class=\"text-warning\"");

WriteLiteral(">Роли</h3>\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
}

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
 using (Ajax.BeginForm("EditRoles", new { controller="users"}, new AjaxOptions { HttpMethod = "post", UpdateTargetId = "roles" , OnBegin="$(this).closest('section').find('button').prepend('<i class=\"fa fa-spin fa-spinner\"></i>&nbsp;')", OnComplete= "removeMessage('#mes-roles')" }))
{
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"userId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 685), Tuple.Create("\"", 702)
            
            #line 19 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
, Tuple.Create(Tuple.Create("", 693), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 693), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <table");

WriteLiteral(" class=\"table table-striped table-condensed roles\"");

WriteLiteral(">\r\n        <tbody>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
            
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
             for (int i = 0; i < roles.Length; i++)
            {
                item = roles[i];
                var hasRole = Model.Roles.FirstOrDefault(x => x.Id == item.Id) != null;

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                         if (!hasRole)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"role\"");

WriteLiteral(" autocomplete=\"off\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1175), Tuple.Create("\"", 1193)
            
            #line 30 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
         , Tuple.Create(Tuple.Create("", 1183), Tuple.Create<System.Object, System.Int32>(item.Name
            
            #line default
            #line hidden
, 1183), false)
);

WriteLiteral(" />\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"role\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" checked");

WriteAttribute("value", Tuple.Create(" value=\"", 1372), Tuple.Create("\"", 1390)
            
            #line 34 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                 , Tuple.Create(Tuple.Create("", 1380), Tuple.Create<System.Object, System.Int32>(item.Name
            
            #line default
            #line hidden
, 1380), false)
);

WriteLiteral(" />\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                    <td>");

            
            #line 37 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                   Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 38 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
                   Write(item.Description);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                </tr>\r\n");

            
            #line 40 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Сохранить</button>\r\n    </div>\r\n");

            
            #line 46 "..\..\Areas\Admin\Views\Users\_UserRoles.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
