#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Users/Edit.cshtml")]
    public partial class _Areas_Admin_Views_Users_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAppUser>
    {
        public _Areas_Admin_Views_Users_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
  
    var isNew = string.IsNullOrEmpty(Model.Id);
    var userName = Model.NikName ?? Model.Email;
    ViewBag.Title = isNew ? "Добавить пользователя" : "Редактировать пользователя \"" + userName + "\"";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        .user .img-circle{\r\n            width:70px;\r\n            border:3px so" +
"lid #ddd;\r\n        }\r\n    </style>\r\n    ");

});

WriteLiteral("\r\n<h2>");

            
            #line 17 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n<div");

WriteLiteral(" class=\"user\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
     if (Model.AvatarId.HasValue)
            {

            
            #line default
            #line hidden
WriteLiteral("        <div>\r\n            <img");

WriteLiteral(" class=\"img-circle\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 551), Tuple.Create("\"", 566)
            
            #line 23 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 557), Tuple.Create<System.Object, System.Int32>(userName
            
            #line default
            #line hidden
, 557), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 567), Tuple.Create("\"", 636)
            
            #line 23 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 573), Tuple.Create<System.Object, System.Int32>(Url.Action("Picture", "Pictures", new { id = Model.AvatarId })
            
            #line default
            #line hidden
, 573), false)
);

WriteLiteral(" />\r\n        </div>\r\n");

            
            #line 25 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n            <section>\r\n                <h3");

WriteLiteral(" class=\"text-warning\"");

WriteLiteral(">Статус</h3>\r\n                <table");

WriteLiteral(" class=\"table table-striped table-condensed\"");

WriteLiteral(">\r\n                    <tbody>\r\n                        <tr>\r\n                   " +
"         <td>Онлайн</td>\r\n                            <td");

WriteLiteral(" class=\"is-online\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 35 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
                                 if (Model.IsOnline)
                                {
            
            #line default
            #line hidden
WriteLiteral("<span");

WriteLiteral(" class=\"badge\"");

WriteLiteral(">Да</span>");

            
            #line 36 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
                                                              }

            
            #line default
            #line hidden
WriteLiteral("                            </td>\r\n                        </tr>\r\n               " +
"         <tr>\r\n                            <td>Email</td>\r\n                     " +
"       <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1315), Tuple.Create("\"", 1341)
, Tuple.Create(Tuple.Create("", 1322), Tuple.Create("mailto:", 1322), true)
            
            #line 41 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1329), Tuple.Create<System.Object, System.Int32>(Model.Email
            
            #line default
            #line hidden
, 1329), false)
);

WriteLiteral(">");

            
            #line 41 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
                                                         Write(Model.Email);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                        </tr>\r\n                    </tbody>\r\n         " +
"       </table>\r\n            </section>\r\n\r\n            <section");

WriteLiteral(" id=\"roles\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
           Write(Html.Partial("_UserRoles", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n\r\n            <section");

WriteLiteral(" id=\"info\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 52 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
           Write(Html.Partial("_UserInfo", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" id=\"subscription\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 58 "..\..\Areas\Admin\Views\Users\Edit.cshtml"
           Write(Html.Partial("_UserReports", new int[] { 1, 2, 3 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        function removeMessage(id) {\r\n            setTimeout(function () {\r\n  " +
"              $(id).fadeOut(\'fast\');\r\n            }, 1000);\r\n        }\r\n\r\n      " +
"  $(function () {\r\n            $(\'#AvatarId\').sx_gvl();\r\n        });\r\n    </scri" +
"pt>\r\n");

});

        }
    }
}
#pragma warning restore 1591
