#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/BannerGroups/Edit.cshtml")]
    public partial class _Areas_Admin_Views_BannerGroups_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMBannerGroup>
    {
        public _Areas_Admin_Views_BannerGroups_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
  
    var isNew = Model.Id == Guid.Empty;
    ViewBag.Title = isNew ? "Добавить группу баннеров" : "Редактировать группу баннеров \"" + Model.Title + "\"";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
     if (!isNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 245), Tuple.Create("\"", 299)
, Tuple.Create(Tuple.Create("", 252), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/lightbox.min.css")
, 252), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
    }

            
            #line default
            #line hidden
});

WriteLiteral("\r\n<h2>");

            
            #line 14 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">\r\n    <b>Внимание!</b> Функционал пока не реализован. Решается вопрос о целесооб" +
"разности внедрения в движок\r\n</div>\r\n\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 584), Tuple.Create("\"", 630)
            
            #line 22 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 593), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "BannerGroups")
            
            #line default
            #line hidden
, 593), false)
);

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
       Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" onclick=\"if (!confirm(\'Удалить запись?\')) { return false;}\"");

WriteLiteral(">Удалить</button>\r\n        </form>\r\n    </div>\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(" role=\"tablist\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#info\"");

WriteLiteral(" aria-controls=\"info\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Основные параметры</a></li>\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
     if (!isNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#banners\"");

WriteLiteral(" aria-controls=\"banners\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Баннеры группы</a></li>\r\n");

            
            #line 36 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n<br />\r\n\r\n<div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"info\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 1356), Tuple.Create("\"", 1400)
            
            #line 42 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1365), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "BannerGroups")
            
            #line default
            #line hidden
, 1365), false)
);

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 43 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
       Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
           Write(Html.LabelFor(x => x.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
           Write(Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите заголовок группы" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 49 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
           Write(Html.LabelFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
           Write(Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите описание группы" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
           Write(Html.ValidationMessageFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
                                                          Write(isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2313), Tuple.Create("\"", 2356)
            
            #line 60 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2320), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "BannerGroups")
            
            #line default
            #line hidden
, 2320), false)
);

WriteLiteral(">Назад</a>\r\n            </div>\r\n        </form>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"banners\"");

WriteLiteral(">\r\n        <h4>Баннеры группы</h4>\r\n\r\n        <div");

WriteLiteral(" id=\"banners-block\"");

WriteLiteral(">\r\n\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

            
            #line 74 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral(@"
        <script>
            $(function () {
                $('#banners-block').sx_gv();

                $('a[href=""#banners""]').on('show.bs.tab', function (e) {
                    $a = $(e.target);

                    $.ajax({
                        method: 'get',
                        url: '");

            
            #line 84 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
                         Write(Url.Action("GroupBanners", "Banners"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                        data: { bgid: \'");

            
            #line 85 "..\..\Areas\Admin\Views\BannerGroups\Edit.cshtml"
                                  Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(@"' },
                        beforeSend: function () {
                            $('a[role=""tab""]').find('.tab-spinner').remove();
                            $a.prepend('<i class=""fa fa-spinner fa-spin tab-spinner""></i>');
                        },
                        success: function (result) {
                            $('#banners-block').html(result);
                        },
                        complete: function () {
                            $a.find('.tab-spinner').remove();
                        }
                    });
                })
            });
        </script>
    ");

});

        }
    }
}
#pragma warning restore 1591
