#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SeoKeywords/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_SeoKeywords__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMSeoKeyword[]>
    {
        public _Areas_Admin_Views_SeoKeywords__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\SeoKeywords\_GridView.cshtml"
  
    int seoTagsId = ViewBag.SeoTagsId;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<br />\r\n<h4>Ключевые слова<span");

WriteLiteral(" class=\"small\"");

WriteLiteral("> (Максимально рекомендуемое количество фраз - 20)</span></h4>\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\SeoKeywords\_GridView.cshtml"
 using (Ajax.BeginForm("edit", new { controller = "SeoKeywords", SeoTagsId = seoTagsId }, new AjaxOptions { HttpMethod = "post", UpdateTargetId = "seo-kw" }))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\SeoKeywords\_GridView.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Admin\Views\SeoKeywords\_GridView.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <label");

WriteLiteral(" for=\"Value\"");

WriteLiteral(">Новое ключевое слово</label>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Value\"");

WriteLiteral(" name=\"Value\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Введите ключевое слово\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Добавить</button>\r\n        </span>\r\n    </div>\r\n");

            
            #line 18 "..\..\Areas\Admin\Views\SeoKeywords\_GridView.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

            
            #line 20 "..\..\Areas\Admin\Views\SeoKeywords\_GridView.cshtml"
Write(Html.SxGridView(Model,
            new SxExtantions.SxGridViewSettings<SxVMSeoKeyword>
            {
                Columns = new SxExtantions.SxGridViewColumn<SxVMSeoKeyword>[]{
                    new SxExtantions.SxGridViewColumn<SxVMSeoKeyword>{FieldName="Value", Caption="Ключевое слово"}
                },
                DataAjaxUrl = Url.Action("Index","SeoKeywords",new { stid= seoTagsId }),
                EnableDeleting = true,
                DeleteRowUrl = x => { return Url.Action("Delete", "SeoKeywords", new { Id= x.Id, SeoTagsId= seoTagsId }); }
            }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
