#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Nets/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_Nets__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMNet[]>
    {
        public _Areas_Admin_Views_Nets__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Nets\_GridView.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Nets\_GridView.cshtml"
Write(Html.SxGridView(Model,
            new SxExtantions.SxGridViewSettings<SxVMNet>
            {
                Columns = new SxExtantions.SxGridViewColumn<SxVMNet>[]{
                    new SxExtantions.SxGridViewColumn<SxVMNet>{FieldName="Code", Caption="Код"},
                    new SxExtantions.SxGridViewColumn<SxVMNet>{FieldName="Name", Caption="Название"},
                    new SxExtantions.SxGridViewColumn<SxVMNet>{FieldName="Url", Caption="Ссылка", Template=x=> {
                        return string.Format("<a href=\"{0}\" target=\"_blank\"><i class=\"fa fa-link\"></i>&nbsp;{0}</a>", x.Url);
                    } },
                    new SxExtantions.SxGridViewColumn<SxVMNet>{FieldName="LogoCssClass", Caption="Логотип", Template=x=> {
                        return string.Format("<i class=\"{0}\"></i>", x.LogoCssClass, x.Color);
                    } },
                    new SxExtantions.SxGridViewColumn<SxVMNet>{FieldName="Color", Caption="Основной цвет (hex)", Template=x=> {
                        return string.Format("<span style=\"color:{0}\">{0}</span>", x.Color);
                    } },
                    new SxExtantions.SxGridViewColumn<SxVMNet>{FieldName="HasCounter", Caption="Поддержка счётчика", Template=x=> {
                        return string.Format("<i class=\"fa {0} {1}\"></i>", x.HasCounter?"fa-check ":"fa-times", x.HasCounter?"text-success":"text-danger");
                    } }
                },
                DataAjaxUrl = Url.Action("Index", "Nets"),
                ShowPagerInfo = true
}
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
