#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SiteNets/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_SiteNets__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMSiteNet[]>
    {
        public _Areas_Admin_Views_SiteNets__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\SiteNets\_GridView.cshtml"
Write(Html.SxGridView(Model,
        new SxExtantions.SxGridViewSettings<SxVMSiteNet>
        {
            Columns = new SxExtantions.SxGridViewColumn<SxVMSiteNet>[]{
                new SxExtantions.SxGridViewColumn<SxVMSiteNet>{FieldName="NetName", Caption="Сеть", Template=x=> { return "<i class=\""+x.Net.LogoCssClass+"\"></i>&nbsp;&nbsp;&nbsp;<span>"+x.NetName+"</span>"; } },
                new SxExtantions.SxGridViewColumn<SxVMSiteNet>{FieldName="Url", Caption="Адрес"},
                new SxExtantions.SxGridViewColumn<SxVMSiteNet>{FieldName="Show", Caption="Показывать", Template=x=> { return x.Show?"Да":"Нет"; } }
            },
            DataAjaxUrl = Url.Action("Index", "SiteNets"),
            EnableEditing = true,
            EditRowUrl = x => { return Url.Action("Edit", "SiteNets", new { id = x.Net.Id }); },
            ShowPagerInfo = true,
            RowCssClass = x => { return x.Url != null && x.Show ? null : "warning"; }
        }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
