#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SiteNets/Edit.cshtml")]
    public partial class _Areas_Admin_Views_SiteNets_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMSiteNet>
    {
        public _Areas_Admin_Views_SiteNets_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
  
    ViewBag.Title = "Редактировать сеть сайта \"" + Model.Net.Name + "\"";

            
            #line default
            #line hidden
WriteLiteral("\n<h2>");

            
            #line 5 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 143), Tuple.Create("\"", 183)
            
            #line 7 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 152), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "SiteNets")
            
            #line default
            #line hidden
, 152), false)
);

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 239), Tuple.Create("\"", 271)
            
            #line 9 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 246), Tuple.Create<System.Object, System.Int32>(Html.NameFor(x=>x.NetId)
            
            #line default
            #line hidden
, 246), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 272), Tuple.Create("\"", 293)
            
            #line 9 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 280), Tuple.Create<System.Object, System.Int32>(Model.Net.Id
            
            #line default
            #line hidden
, 280), false)
);

WriteLiteral(" />\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
   Write(Html.LabelFor(x => x.Url, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
   Write(Html.EditorFor(x => x.Url, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Url));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
   Write(Html.LabelFor(x => x.Show, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 17 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
   Write(Html.EditorFor(x => x.Show, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Show));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Сохранить</button>\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 913), Tuple.Create("\"", 940)
            
            #line 22 "..\..\Areas\Admin\Views\SiteNets\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 920), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 920), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Назад</a>\n    </div>\n</form>\n\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1025), Tuple.Create("\"", 1083)
, Tuple.Create(Tuple.Create("", 1031), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 1031), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1106), Tuple.Create("\"", 1176)
, Tuple.Create(Tuple.Create("", 1112), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 1112), false)
);

WriteLiteral("></script>\n");

});

        }
    }
}
#pragma warning restore 1591
