#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SeoTags/_EditForMaterial.cshtml")]
    public partial class _Areas_Admin_Views_SeoTags__EditForMaterial_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMSeoTags>
    {
        public _Areas_Admin_Views_SeoTags__EditForMaterial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
  
    var isNew = Model.SeoTitle == null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
 if (ViewBag.SeoInfoRedactInfo != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-info message\"");

WriteLiteral(">");

            
            #line 9 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
                                     Write(ViewBag.SeoInfoRedactInfo);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
 using (Ajax.BeginForm("EditForMaterial", new { controller = "SeoTags" }, new AjaxOptions { HttpMethod = "post", UpdateTargetId = "seo-block", OnBegin = "$('#btn-save-seo-tag').prepend('<i class=\"fa fa-spinner fa-spin\"></i>')", OnSuccess = "$('#seo-kw').sx_gv(); setTimeout(function(){$('.alert-info.message').fadeOut();}, 1000)" }))
{
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
                              
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
Write(Html.HiddenFor(x => x.MaterialId));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
Write(Html.HiddenFor(x => x.ModelCoreType));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
                                         

    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
                            

    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
Write(Html.Partial("_GeneralEdit", Model));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
                                        


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" id=\"btn-save-seo-tag\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
                                                                        Write(isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        <a");

WriteLiteral(" href=\"#info\"");

WriteLiteral(" aria-controls=\"info\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"$(\'a[href=&quot;#info&quot;]\').tab(\'show\'); return false;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-long-arrow-left\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>&nbsp;Параметры</a>\r\n    </div>\r\n");

            
            #line 26 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"seo-kw\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
   Write(Html.Action("Index", "SeoKeywords", new { stid=Model.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\SeoTags\_EditForMaterial.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
