#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SeoTags/_GeneralEdit.cshtml")]
    public partial class _Areas_Admin_Views_SeoTags__GeneralEdit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMSeoTags>
    {
        public _Areas_Admin_Views_SeoTags__GeneralEdit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
Write(Html.LabelFor(x => x.SeoTitle, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <span");

WriteLiteral(" class=\"text-info\"");

WriteLiteral("> (тег Title. Обязательная длина - 7-15 слов)</span>\r\n");

WriteLiteral("    ");

            
            #line 6 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
Write(Html.EditorFor(x => x.SeoTitle, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите заголовок страницы", @autocomplete = "off" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
Write(Html.ValidationMessageFor(x => x.SeoTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
Write(Html.LabelFor(x => x.SeoDescription, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <span");

WriteLiteral(" class=\"text-info\"");

WriteLiteral("> (тег Description. Обязательная длина - 150-700 знаков)</span>\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
Write(Html.EditorFor(x => x.SeoDescription, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите описание страницы", @autocomplete = "off" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
Write(Html.ValidationMessageFor(x => x.SeoDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
       Write(Html.LabelFor(x => x.H1, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <span");

WriteLiteral(" class=\"text-info\"");

WriteLiteral("> (тег h1. Обязательная длина - 2-8 слов. Тег отображается непосредственно перед " +
"началом любого полезного контента страницы.)</span>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
       Write(Html.EditorFor(x => x.H1, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите тег h1", @autocomplete = "off" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
       Write(Html.ValidationMessageFor(x => x.H1));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
       Write(Html.LabelFor(x => x.H1CssClass, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
       Write(Html.EditorFor(x => x.H1CssClass, new { htmlAttributes = new { @class = "form-control", @placeholder = "Css стиль тега h1", @autocomplete = "off" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Areas\Admin\Views\SeoTags\_GeneralEdit.cshtml"
       Write(Html.ValidationMessageFor(x => x.H1CssClass));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
