#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SeoTags/Index.cshtml")]
    public partial class _Areas_Admin_Views_SeoTags_Index_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMSeoTags[]>
    {
        public _Areas_Admin_Views_SeoTags_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\SeoTags\Index.cshtml"
  
    ViewBag.Title = "Адресные SEO теги";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Areas\Admin\Views\SeoTags\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n<div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(@">
    <strong>Информация!</strong> На этой странице задаются поисковые теги для любой страницы сайта. Теги, заданные на этой странице, являются переопределяющими, т.е. если для какой-то страницы сайта в этом разделе заданы теги, то теги страницы переопределяться заданными здесь.
</div>

<div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(@">
    <strong>Внимание!</strong> Если изменен строковый ключ материала, - измениться его каноническая ссылка. Поэтому при изменении строкового ключа необходимо заменить адрес страницы в этом разделе в соответствии со вновь сформированной ссылкой.
</div>

<div");

WriteLiteral(" id=\"grid-seo-tags\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Areas\Admin\Views\SeoTags\Index.cshtml"
Write(Html.Partial("_GridView", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n            $(\'#grid-seo-tags\').sx_gv();" +
"\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
