#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/PictureLinks/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_PictureLinks__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMPicture[]>
    {
        public _Areas_Admin_Views_PictureLinks__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\PictureLinks\_GridView.cshtml"
  
    Layout = null;
    int mid = ViewBag.MaterialId;
    SX.WebCore.Enums.ModelCoreType mct = ViewBag.ModelCoreType;

            
            #line default
            #line hidden
WriteLiteral("\n\n\n");

            
            #line 9 "..\..\Areas\Admin\Views\PictureLinks\_GridView.cshtml"
Write(Html.SxGridView(Model,
            new SxExtantions.SxGridViewSettings<SxVMPicture>
            {
                Columns = new SxExtantions.SxGridViewColumn<SxVMPicture>[]{
                    new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Id", Caption="Идентификатор"},
                    new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Caption", Caption="Наименование"}
                },
                DataAjaxUrl = Url.Action("Index", "PictureLinks", new { mid = mid, mct = mct }),
                EnableDeleting = true,
                DeleteRowUrl = x => { return Url.Action("DeleteMaterialPicture", "PictureLinks", new { mid = mid, mct = mct, pid = x.Id }); },
                EnableCreating = true,
                CreateRowUrl = "javascript:void(0)",
                ShowPagerInfo=true
            }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
