#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/PictureLinks/_GridViewNotLinked.cshtml")]
    public partial class _Areas_Admin_Views_PictureLinks__GridViewNotLinked_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMPicture[]>
    {
        public _Areas_Admin_Views_PictureLinks__GridViewNotLinked_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\PictureLinks\_GridViewNotLinked.cshtml"
  
    Layout = null;
    int mid = ViewBag.MaterialId;
    SX.WebCore.Enums.ModelCoreType mct = ViewBag.ModelCoreType;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\PictureLinks\_GridViewNotLinked.cshtml"
Write(Html.SxGridView(Model,
            new SxExtantions.SxGridViewSettings<SxVMPicture>
            {
                Columns = new SxExtantions.SxGridViewColumn<SxVMPicture>[]{
                    new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Id", Caption="Идентификатор фото"},
                    new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Caption", Caption="Название фото"},
                    new SxExtantions.SxGridViewColumn<SxVMPicture> { FieldName="Width", Caption="Просмотр", ColumnCssClass=x=> { return "col-cm"; }, Template=x=> {
                        return string.Format("<a data-lightbox=\"roadtrip\" data-title=\"{1}\" data-toggle=\"tooltip\" title=\"Помотреть картинку\" href=\"/pictures/picture/{0}\"><i class=\"fa fa-picture-o\"></i></a>", x.Id, x.Caption);
                    }, EnableSorting=false }
                },
                DataAjaxUrl = Url.Action("IndexNotlinked", "PictureLinks", new { mid = mid, mct = mct, fm = false }),
                ShowSelectedCheckbox = true,
                RowId = x => { return x.Id.ToString(); },
                ShowPagerInfo=true
            }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
