#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SiteSettings/EditSite.cshtml")]
    public partial class _Areas_Admin_Views_SiteSettings_EditSite_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMSiteSettings>
    {
        public _Areas_Admin_Views_SiteSettings_EditSite_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
  
    ViewBag.Title = "Настройки сайта";

            
            #line default
            #line hidden
WriteLiteral("\n");

DefineSection("styles", () => {

WriteLiteral("\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 94), Tuple.Create("\"", 148)
, Tuple.Create(Tuple.Create("", 101), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/lightbox.min.css")
, 101), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\n        .grid-pictures tbody > tr > td:last-child {\n            text-align: cen" +
"ter;\n            vertical-align: middle;\n        }\n    </style>\n");

});

WriteLiteral("<h2>");

            
            #line 14 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n<br />\n");

            
            #line 16 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
 if (ViewBag.EditSiteSettingsMessage != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 18 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                       Write(ViewBag.EditSiteSettingsMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\n");

            
            #line 19 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 508), Tuple.Create("\"", 555)
            
            #line 20 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
, Tuple.Create(Tuple.Create("", 517), Tuple.Create<System.Object, System.Int32>(Url.Action("Editsite","SiteSettings")
            
            #line default
            #line hidden
, 517), false)
);

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(Html.HiddenFor(x => x.OldSiteDomain));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(Html.HiddenFor(x => x.OldLogoPath));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(Html.HiddenFor(x => x.OldSiteName));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(Html.HiddenFor(x => x.OldSiteBgPath));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 26 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(Html.HiddenFor(x => x.OldSiteFaveiconPath));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
Write(Html.HiddenFor(x => x.OldSiteDesc));

            
            #line default
            #line hidden
WriteLiteral("\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.LabelFor(x => x.SiteDomain, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.EditorFor(x => x.SiteDomain, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите домен управляемого сайта" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.ValidationMessageFor(x => x.SiteDomain));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.LabelFor(x => x.SiteName, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.EditorFor(x => x.SiteName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите наименование сайта" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.ValidationMessageFor(x => x.SiteName));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n    </div>\n\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.LabelFor(x => x.LogoPath, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 49 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                
            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                 if (!string.IsNullOrEmpty(Model.LogoPath))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" style=\"margin-left:15px;\"");

WriteLiteral(" data-lightbox=\"roadtrip\"");

WriteLiteral(" data-title=\"aaa\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" title=\"Помотреть картинку\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2085), Tuple.Create("\"", 2155)
            
            #line 51 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                                                                  , Tuple.Create(Tuple.Create("", 2092), Tuple.Create<System.Object, System.Int32>(Url.Action("Picture", "Pictures", new { id = Model.LogoPath })
            
            #line default
            #line hidden
, 2092), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-picture-o\"");

WriteLiteral("></i></a>\n");

            
            #line 52 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 53 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.EditorFor(x => x.LogoPath, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите путь к изображению" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.ValidationMessageFor(x => x.LogoPath));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n        <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 59 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.LabelFor(x => x.SiteBgPath, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 60 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                
            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                 if (!string.IsNullOrEmpty(Model.SiteBgPath))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" style=\"margin-left:15px;\"");

WriteLiteral(" data-lightbox=\"roadtrip\"");

WriteLiteral(" data-title=\"aaa\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" title=\"Помотреть картинку\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2828), Tuple.Create("\"", 2900)
            
            #line 62 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                                                                  , Tuple.Create(Tuple.Create("", 2835), Tuple.Create<System.Object, System.Int32>(Url.Action("Picture", "Pictures", new { id = Model.SiteBgPath })
            
            #line default
            #line hidden
, 2835), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-picture-o\"");

WriteLiteral("></i></a>\n");

            
            #line 63 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 64 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.EditorFor(x => x.SiteBgPath, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите путь к файлу фона" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 65 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.ValidationMessageFor(x => x.SiteBgPath));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n        <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 70 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.LabelFor(x => x.SiteFaveiconPath, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"text-info\"");

WriteLiteral("> (faveicon)</span>\n");

            
            #line 71 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                
            
            #line default
            #line hidden
            
            #line 71 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                 if (!string.IsNullOrEmpty(Model.SiteFaveiconPath))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" style=\"margin-left:15px;\"");

WriteLiteral(" data-lightbox=\"roadtrip\"");

WriteLiteral(" data-title=\"aaa\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" title=\"Помотреть картинку\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3631), Tuple.Create("\"", 3709)
            
            #line 73 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                                                                  , Tuple.Create(Tuple.Create("", 3638), Tuple.Create<System.Object, System.Int32>(Url.Action("Picture", "Pictures", new { id = Model.SiteFaveiconPath })
            
            #line default
            #line hidden
, 3638), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-picture-o\"");

WriteLiteral("></i></a>\n");

            
            #line 74 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 75 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.EditorFor(x => x.SiteFaveiconPath, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите путь к файлу фона" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
           Write(Html.ValidationMessageFor(x => x.SiteFaveiconPath));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n        </div>\n    </div>\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 81 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
   Write(Html.LabelFor(x => x.SiteDesc, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 82 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
   Write(Html.EditorFor(x => x.SiteDesc, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите описание сайта" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 83 "..\..\Areas\Admin\Views\SiteSettings\EditSite.cshtml"
   Write(Html.ValidationMessageFor(x => x.SiteDesc));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Сохранить</button>\n    </div>\n</form>\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4493), Tuple.Create("\"", 4538)
, Tuple.Create(Tuple.Create("", 4499), Tuple.Create<System.Object, System.Int32>(Href("~/bower_components/ckeditor/ckeditor.js")
, 4499), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4561), Tuple.Create("\"", 4612)
, Tuple.Create(Tuple.Create("", 4567), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/lightbox.min.js")
, 4567), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4635), Tuple.Create("\"", 4693)
, Tuple.Create(Tuple.Create("", 4641), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 4641), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4716), Tuple.Create("\"", 4786)
, Tuple.Create(Tuple.Create("", 4722), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 4722), false)
);

WriteLiteral(@"></script>
    <script>
        if (CKEDITOR.instances['SiteDesc']) {
            CKEDITOR.remove(CKEDITOR.instances['SiteDesc']);
        }
        CKEDITOR.replace('SiteDesc', { height: 300 });

        $(function () {
            $('#LogoPath, #SiteBgPath, #SiteFaveiconPath').sx_gvl();

            $('#LogoPath').on('click', 'a', function (event) {
                event.stopPropagation();
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
