#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/SiteSettings/ReleaseNotes.cshtml")]
    public partial class _Areas_Admin_Views_SiteSettings_ReleaseNotes_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<string>
    {
        public _Areas_Admin_Views_SiteSettings_ReleaseNotes_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\SiteSettings\ReleaseNotes.cshtml"
  
    ViewBag.Title = "История выпусков";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Areas\Admin\Views\SiteSettings\ReleaseNotes.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n<div");

WriteLiteral(" class=\"release-notes\"");

WriteLiteral(">\r\n    <pre>\r\n");

WriteLiteral("        ");

            
            #line 10 "..\..\Areas\Admin\Views\SiteSettings\ReleaseNotes.cshtml"
   Write(Model);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </pre>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
