#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Pictures/_FindGridView.cshtml")]
    public partial class _Areas_Admin_Views_Pictures__FindGridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMPicture[]>
    {
        public _Areas_Admin_Views_Pictures__FindGridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Pictures\_FindGridView.cshtml"
Write(Html.SxGridView(Model,
    new SxExtantions.SxGridViewSettings<SxVMPicture>
    {
        Columns = new SxExtantions.SxGridViewColumn<SxVMPicture>[]{
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Caption", Caption="Картинка", ColumnCssClass=x=> { return "word-wrap"; } },
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Width", Caption="Ширина" },
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Height", Caption="Высота" },
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Id", Caption="Картинка", Template=x=> {return string.Format("<a onclick=\"x()\" data-lightbox=\"roadtrip\" data-title=\"{1}\" data-toggle=\"tooltip\" title=\"Помотреть картинку\" href=\"/pictures/picture/{0}\"><i class=\"fa fa-picture-o\"></i></a>", x.Id, x.Caption); }, ColumnCssClass=x=> {return "col-cm col-img"; } }
        },
        DataAjaxUrl= Url.Action("FindGridView", "Pictures"),
        RowId = x => { return x.Id.ToString(); },
        RowText = x => { return x.Caption; },
    },
        htmlAttributes: new { @class="grid-pictures"}
));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
