#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Pictures/_FreePictures.cshtml")]
    public partial class _Areas_Admin_Views_Pictures__FreePictures_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMPicture[]>
    {
        public _Areas_Admin_Views_Pictures__FreePictures_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Pictures\_FreePictures.cshtml"
Write(Html.SxGridView(Model, new SxExtantions.SxGridViewSettings<SxVMPicture> {
    Columns=new SxExtantions.SxGridViewColumn<SxVMPicture>[] {
        new SxExtantions.SxGridViewColumn<SxVMPicture> { FieldName="DateCreate", Caption="Дата занесения в БД" },
        new SxExtantions.SxGridViewColumn<SxVMPicture> { FieldName="Caption", Caption="Наименование" },
        new SxExtantions.SxGridViewColumn<SxVMPicture> { FieldName="Size", Caption="Размер, kB", Template=x=> {
            return Math.Round((decimal)x.Size/1024, 2).ToString();
        } },
        new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Id", Caption="Картинка", Template=(p)=> {
                return string.Format("<a data-lightbox=\"roadtrip\" data-title=\"{1}\" data-toggle=\"tooltip\" title=\"Помотреть картинку\" href=\"/pictures/picture/{0}\"><i class=\"fa fa-picture-o\"></i></a>", p.Id, p.Caption);
            }, ColumnCssClass=x=> { return "col-cm"; } }
    },
    DataAjaxUrl=Url.Action("FreePictures", "Pictures"),
    ShowPagerInfo=true
}));

            
            #line default
            #line hidden
WriteLiteral("\n");

        }
    }
}
#pragma warning restore 1591
