#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Pictures/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_Pictures__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMPicture[]>
    {
        public _Areas_Admin_Views_Pictures__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Pictures\_GridView.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Pictures\_GridView.cshtml"
Write(Html.SxGridView(Model,
        new SxExtantions.SxGridViewSettings<SxVMPicture>
        {
            Columns = new SxExtantions.SxGridViewColumn<SxVMPicture>[]{
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Id", Caption="Идентификатор", Template=(p)=> {
                return string.Format("<b class=\"text-info\">{0}</b>", p.Id);
            } },
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Caption", Caption="Название"},
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Description", Caption="Описание"},
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Width", Caption="Ширина, px"},
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Height", Caption="Высота, px"},
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Size", Caption="Размер, Kb", Template=(p)=> {
                return string.Format("<span>{0}</span>", Math.Round((double)p.Size/1024, 2));
            } },
            new SxExtantions.SxGridViewColumn<SxVMPicture>{FieldName="Id", Caption="Картинка", Template=(p)=> {
                return string.Format("<a data-lightbox=\"roadtrip\" data-title=\"{1}\" data-toggle=\"tooltip\" title=\"Помотреть картинку\" href=\"/pictures/picture/{0}\"><i class=\"fa fa-picture-o\"></i></a>", p.Id, p.Caption);
            } }
        },
            EnableCreating = true,
            CreateRowUrl = Url.Action("Edit", "Pictures"),
            EnableEditing = true,
            EditRowUrl = (x) => { return Url.Action("Edit", "Pictures", new { id=x.Id }); },
            DataAjaxUrl = Url.Action("Index","Pictures"),
            ShowPagerInfo=true
        }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
