#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Pictures/Edit.cshtml")]
    public partial class _Areas_Admin_Views_Pictures_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMPicture>
    {
        public _Areas_Admin_Views_Pictures_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
  
    var isNew = Model.Id == Guid.Empty;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
Write(isNew ? "Добавить фото" : "Редактировать фото");

            
            #line default
            #line hidden
WriteLiteral("\r\n</h2>\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 178), Tuple.Create("\"", 220)
            
            #line 11 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 187), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "Pictures")
            
            #line default
            #line hidden
, 187), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
   Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger pull-right\"");

WriteLiteral(" onclick=\"if(!confirm(\'Удалить запись?\')){return false;}\"");

WriteLiteral(">Удалить фото</button>\r\n    </form>\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 481), Tuple.Create("\"", 521)
            
            #line 18 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 490), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "Pictures")
            
            #line default
            #line hidden
, 490), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
Write(Html.HiddenFor(x => x.ImgFormat));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
       Write(Html.LabelFor(x => x.Caption, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 26 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
       Write(Html.EditorFor(x => x.Caption, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
       Write(Html.ValidationMessageFor(x => x.Caption));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 33 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
       Write(Html.LabelFor(x => x.Description, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
       Write(Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 35 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
       Write(Html.ValidationMessageFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <br />\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Выбор фото</label>\r\n            <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" name=\"file\"");

WriteLiteral(" class=\"hidden\"");

WriteLiteral(" />\r\n            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control select-input\"");

WriteLiteral(" placeholder=\"Выберите изображение\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-default select-btn\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">Выбрать</button>\r\n                </span>\r\n            </div>\r\n        </div>\r\n " +
"   </div>\r\n    <br />\r\n");

            
            #line 53 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
     if (!isNew)
    {

            
            #line default
            #line hidden
WriteLiteral("        <img");

WriteAttribute("alt", Tuple.Create(" alt=\"", 1927), Tuple.Create("\"", 1947)
            
            #line 55 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1933), Tuple.Create<System.Object, System.Int32>(Model.Caption
            
            #line default
            #line hidden
, 1933), false)
);

WriteAttribute("src", Tuple.Create(" src=\"", 1948), Tuple.Create("\"", 1981)
, Tuple.Create(Tuple.Create("", 1954), Tuple.Create("/pictures/picture/", 1954), true)
            
            #line 55 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1972), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 1972), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("        <br />\r\n");

            
            #line 57 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 62 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
                                                          Write(Model.Id == Guid.Empty ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2259), Tuple.Create("\"", 2298)
            
            #line 63 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2266), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Pictures")
            
            #line default
            #line hidden
, 2266), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Назад</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</form>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2424), Tuple.Create("\"", 2482)
, Tuple.Create(Tuple.Create("", 2430), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 2430), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2506), Tuple.Create("\"", 2576)
, Tuple.Create(Tuple.Create("", 2512), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 2512), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            $(\'[type=\"file\"]\').change(function (e) {\r" +
"\n                var file = e.target.files[0];\r\n");

            
            #line 76 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 76 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
                 if(isNew)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("\r\n                $(\'#Caption\').val(file.name);\r\n                $(\'#Description\'" +
").val(\'Name: \' + file.name + \'\\nType: \' + file.type + \'\\nSize: \' + file.size + \'" +
" byte\');\r\n                $(\'#ImgFormat\').val(file.type);\r\n                ");

WriteLiteral("\r\n");

            
            #line 83 "..\..\Areas\Admin\Views\Pictures\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral(@"                $('.select-input').val(file.name);
            });

            $('.select-btn').click(function () {
                $(this).closest('.input-group').prev('[type=""file""]').click();
            });

            $('.select-input').click(function () {
                $(this).closest('.input-group').find('.select-btn').trigger('click');
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
