#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Pictures/Index.cshtml")]
    public partial class _Areas_Admin_Views_Pictures_Index_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMPicture[]>
    {
        public _Areas_Admin_Views_Pictures_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
  
    ViewBag.Title = "Фото-контент";

            
            #line default
            #line hidden
WriteLiteral("\n\n");

DefineSection("styles", () => {

WriteLiteral("\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 89), Tuple.Create("\"", 143)
, Tuple.Create(Tuple.Create("", 96), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/lightbox.min.css")
, 96), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\n    <style>\n        #grid-pictures tbody > tr:not(.empty-data-row) > td:last-" +
"child{\n            text-align:center;\n            vertical-align:middle;\n       " +
" }\n    </style>\n");

});

WriteLiteral("\n\n\n<h2>");

            
            #line 18 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n<div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">\n    <strong>Внимание!</strong> При добалении изображений не допускайте разраста" +
"ния базы данных. Размер добавляемого файла не должен превышать <b>");

            
            #line 20 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
                                                                                                                                             Write(int.Parse(System.Configuration.ConfigurationManager.AppSettings["MaxPictureLength"])/1024);

            
            #line default
            #line hidden
WriteLiteral(" Kb</b>. Перед добавлением рекомендуется сжать изображение специализированным onl" +
"ine-сервисом (например <a");

WriteLiteral(" href=\"http://resizepiconline.com\"");

WriteLiteral(" rel=\"nofollow\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><b>http://resizepiconline.com</b></a>)\n</div>\n<div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 937), Tuple.Create("\"", 979)
            
            #line 24 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
, Tuple.Create(Tuple.Create("", 946), Tuple.Create<System.Object, System.Int32>(Url.Action("AddMany","Pictures")
            
            #line default
            #line hidden
, 946), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(" id=\"multiform\"");

WriteLiteral(">\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n            <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" name=\"files\"");

WriteLiteral(" id=\"files\"");

WriteLiteral(" class=\"hidden\"");

WriteLiteral(" multiple />\n        </form>\n        <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" onclick=\"$(\'#files\').click(); return false;\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i> Множественное добавление</a>\n        <button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#delPicturesModel\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-trash\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i> Очистить</button>\n    </div>\n</div>\n<div");

WriteLiteral(" id=\"grid-pictures\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 33 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
Write(Html.Partial("_GridView", Model));

            
            #line default
            #line hidden
WriteLiteral("\n</div>\n\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" id=\"delPicturesModel\"");

WriteLiteral(">\n");

            
            #line 37 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
     using (Ajax.BeginForm("DeleteFreePictures", new { controller = "Pictures" }, new AjaxOptions { HttpMethod = "post", OnBegin= "$('#delPicturesModel .progress').show()", OnSuccess= "$('#delPicturesModel').modal('hide'); $('#delPicturesModel .progress').hide(); alert('Фото успешно очищены!');", OnFailure= "$('#delPicturesModel .progress').hide()", UpdateTargetId= "grid-pictures" }))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\n                    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Очистка БД изображений</h4>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\n                    <div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">\n                        <strong>Внимание!</strong> При удалении не удаляются фо" +
"то, используемые в разметке материалов.\n                    </div>\n             " +
"       <div");

WriteLiteral(" id=\"freePictures\"");

WriteLiteral(">\n\n                    </div>\n                </div>\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\n                        <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"progress\"");

WriteLiteral(" style=\"margin: 0px; position: relative; top: 7px; display:none;\"");

WriteLiteral(">\n                                <div");

WriteLiteral(" class=\"progress-bar progress-bar-striped active\"");

WriteLiteral(" role=\"progressbar\"");

WriteLiteral(" aria-valuenow=\"100\"");

WriteLiteral(" aria-valuemin=\"0\"");

WriteLiteral(" aria-valuemax=\"100\"");

WriteLiteral(" style=\"width: 100%\"");

WriteLiteral(">\n                                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">100% Complete</span>\n                                </div>\n                    " +
"        </div>\n                        </div>\n                        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\n                            <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Закрыть</button>\n                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Приступить</button>\n                            </div>\n                        <" +
"/div>\n                    </div>\n                </div>\n            </div>\n     " +
"   </div>\n");

            
            #line 72 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\n\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3896), Tuple.Create("\"", 3947)
, Tuple.Create(Tuple.Create("", 3902), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/lightbox.min.js")
, 3902), false)
);

WriteLiteral(@"></script>
    <script>
        $(function () {
            $('#grid-pictures, #freePictures').sx_gv();

            $('#files').change(function () {
                $('#multiform').submit();
            });

            $('#delPicturesModel').on('show.bs.modal', function (e) {
                $body = $('#freePictures');
                $.ajax({
                    method: 'get',
                    url: '");

            
            #line 89 "..\..\Areas\Admin\Views\Pictures\Index.cshtml"
                     Write(Url.Action("FreePictures", "Pictures"));

            
            #line default
            #line hidden
WriteLiteral("\',\n                    success: function (result) {\n                        $body" +
".html(result);\n                        $body.find(\'[data-toggle=\"tooltip\"]\').too" +
"ltip();\n                    }\n                });\n            })\n        });\n   " +
" </script>\n");

});

        }
    }
}
#pragma warning restore 1591
