#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Requests/Index.cshtml")]
    public partial class _Areas_Admin_Views_Requests_Index_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMRequest[]>
    {
        public _Areas_Admin_Views_Requests_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Requests\Index.cshtml"
  
    ViewBag.Title = "Статистика запросов";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 102), Tuple.Create("\"", 150)
, Tuple.Create(Tuple.Create("", 109), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/css/morris.css")
, 109), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("\r\n<h2>");

            
            #line 10 "..\..\Areas\Admin\Views\Requests\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<br />\r\n\r\n<ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(" role=\"tablist\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#data\"");

WriteLiteral(" aria-controls=\"data\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Данные</a></li>\r\n    <li");

WriteLiteral(" role=\"presentation\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#graf\"");

WriteLiteral(" aria-controls=\"graf\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Графики</a></li>\r\n</ul>\r\n<div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"data\"");

WriteLiteral(">\r\n        <br />\r\n        <div");

WriteLiteral(" id=\"grid\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Areas\Admin\Views\Requests\Index.cshtml"
       Write(Html.Partial("_GridView", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"graf\"");

WriteLiteral(">\r\n        <br />\r\n        <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\r\n            <strong>Информация!</strong> Графики разработаны с помощью <a");

WriteLiteral(" href=\"https://morrisjs.github.io/morris.js/\"");

WriteLiteral("><b>https://morrisjs.github.io/morris.js/</b></a>\r\n        </div>\r\n        <h4>Ст" +
"атистика за последний месяц</h4>\r\n        <div");

WriteLiteral(" id=\"request-stat\"");

WriteLiteral(" style=\"height: 250px;\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1161), Tuple.Create("\"", 1211)
, Tuple.Create(Tuple.Create("", 1167), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/raphael.min.js")
, 1167), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1235), Tuple.Create("\"", 1284)
, Tuple.Create(Tuple.Create("", 1241), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/morris.min.js")
, 1241), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\'#grid\').sx_gv()" +
";\r\n\r\n            $(\'a[href=\"#graf\"]\').on(\'shown.bs.tab\', function (e) {\r\n       " +
"         $.ajax({\r\n                    url: \'");

            
            #line 43 "..\..\Areas\Admin\Views\Requests\Index.cshtml"
                     Write(Url.Action("DateStatistic", "Requests"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                    method: 'get',
                    contentType: ""application/json; charset=utf-8"",
                    beforeSend: function () {
                        $('#request-stat').html('');
                    },
                    success: function (data) {
                        new Morris.Bar({
                            element: 'request-stat',
                            data: data,
                            xkey: 'DateCreate',
                            ykeys: ['Count'],
                            labels: [""Количество:""],
                            xLabelFormat: function (o) {
                                var d = new Date(parseInt(o.label.substring(6)));
                                return d.getDate() + '/' + (d.getMonth() + 1) + '/' + d.getFullYear();
                            }
                        });
                    }
                });
            })
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
