#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ShareButtons/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_ShareButtons__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMShareButton[]>
    {
        public _Areas_Admin_Views_ShareButtons__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\ShareButtons\_GridView.cshtml"
Write(Html.SxGridView(Model,
            new SxExtantions.SxGridViewSettings<SxVMShareButton>
            {
                Columns = new SxExtantions.SxGridViewColumn<SxVMShareButton>[]{
                    new SxExtantions.SxGridViewColumn<SxVMShareButton>{FieldName="NetName", Caption="Сеть", Template=x=> {
                        return string.Format("<small>{0}</small><br/><i class=\"{1}\"></i>", x.NetName, x.Net.LogoCssClass);
                    }, ColumnCssClass=x=> { return "col-first"; } },
                    new SxExtantions.SxGridViewColumn<SxVMShareButton>{FieldName="Show", Caption="Показывать", Template=x=> {
                        return string.Format("<i class=\"fa {0} {1}\"></i>", x.Show?"fa-check ":"fa-times", x.Show?"text-success":"text-danger");
                    } },
                    new SxExtantions.SxGridViewColumn<SxVMShareButton>{FieldName="ShowCounter", Caption="Показывать счетчик", Template=x=> {
                        return !x.Net.HasCounter?null: string.Format("<i class=\"fa {0} {1}\"></i>", x.ShowCounter?"fa-check ":"fa-times", x.ShowCounter?"text-success":"text-danger");
                    } }
                },
                EnableEditing = true,
                EditRowUrl = (x) => { return Url.Action("Edit", "ShareButtons", new { id = x.Id }); },
                DataAjaxUrl = Url.Action("Index", "ShareButtons"),
                ShowPagerInfo=true,
                RowCssClass = (x) => { return x.Show ? null : "warning"; }
            }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
