#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ShareButtons/Edit.cshtml")]
    public partial class _Areas_Admin_Views_ShareButtons_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMShareButton>
    {
        public _Areas_Admin_Views_ShareButtons_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
  
    var isNew = Model.Id == 0;
    ViewBag.Title = "Редактировать кнопку шар для сети "+Model.Net.Name;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 185), Tuple.Create("\"", 228)
            
            #line 9 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 194), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit","ShareButtons")
            
            #line default
            #line hidden
, 194), false)
);

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
         if (Model.Net.HasCounter)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.LabelFor(x => x.Show, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 19 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.EditorFor(x => x.Show, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 20 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.ValidationMessageFor(x => x.Show));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.LabelFor(x => x.ShowCounter, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.EditorFor(x => x.ShowCounter, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.ValidationMessageFor(x => x.ShowCounter));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.LabelFor(x => x.Show, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.EditorFor(x => x.Show, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 37 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
               Write(Html.ValidationMessageFor(x => x.Show));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n");

            
            #line 40 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 45 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
                                                  Write(isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1732), Tuple.Create("\"", 1774)
            
            #line 46 "..\..\Areas\Admin\Views\ShareButtons\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1739), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","ShareButtons")
            
            #line default
            #line hidden
, 1739), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Назад</a>\r\n    </div>\r\n</form>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1864), Tuple.Create("\"", 1910)
, Tuple.Create(Tuple.Create("", 1870), Tuple.Create<System.Object, System.Int32>(Href("~/content/dist/js/jquery.validate.min.js")
, 1870), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1934), Tuple.Create("\"", 1992)
, Tuple.Create(Tuple.Create("", 1940), Tuple.Create<System.Object, System.Int32>(Href("~/content/dist/js/jquery.validate.unobtrusive.min.js")
, 1940), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
