#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Seo/EditRobotsFile.cshtml")]
    public partial class _Areas_Admin_Views_Seo_EditRobotsFile_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMRobotsFile>
    {
        public _Areas_Admin_Views_Seo_EditRobotsFile_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
  
    ViewBag.Title = "Содержание Robots.txt";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<br />\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
 if (ViewBag.EditSiteSettingsMessage != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 10 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
                       Write(ViewBag.EditSiteSettingsMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 251), Tuple.Create("\"", 295)
            
            #line 13 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
, Tuple.Create(Tuple.Create("", 260), Tuple.Create<System.Object, System.Int32>(Url.Action("EditRobotsFile","Seo")
            
            #line default
            #line hidden
, 260), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
Write(Html.HiddenFor(x => x.OldFileContent));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
   Write(Html.LabelFor(x => x.FileContent, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
   Write(Html.EditorFor(x => x.FileContent, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите содержание файла", @style = "min-height:400px;" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 20 "..\..\Areas\Admin\Views\Seo\EditRobotsFile.cshtml"
   Write(Html.ValidationMessageFor(x => x.FileContent));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Сохранить</button>\r\n    </div>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
