#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/AffiliateLinks/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_AffiliateLinks__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAffiliateLink[]>
    {
        public _Areas_Admin_Views_AffiliateLinks__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\AffiliateLinks\_GridView.cshtml"
Write(Html.SxGridView(Model,
        new SxExtantions.SxGridViewSettings<SxVMAffiliateLink>
        {
            Columns = new SxExtantions.SxGridViewColumn<SxVMAffiliateLink>[]{
                new SxExtantions.SxGridViewColumn<SxVMAffiliateLink>{FieldName="Id", Caption="Идентификатор", Template=x=> { return "<b class=\"text-info\">"+x.Id+"</b>"; } },
                new SxExtantions.SxGridViewColumn<SxVMAffiliateLink>{FieldName="ClickCost", Caption="Стоимость клика, руб.", Template=x=> {
                    return Math.Round((decimal)x.ClickCost, 2).ToString();
                } },
                new SxExtantions.SxGridViewColumn<SxVMAffiliateLink>{FieldName="ViewsCount", Caption="Кол-во переходов"}
            },
            DataAjaxUrl = Url.Action("Index", "AffiliateLinks"),
            EnableCreating = true,
            CreateRowUrl = Url.Action("Edit", "AffiliateLinks"),
            EnableEditing = true,
            EditRowUrl = x => { return Url.Action("Edit", "AffiliateLinks", new { id=x.Id}); },
            ShowPagerInfo=true
        }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
