#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/AffiliateLinks/Edit.cshtml")]
    public partial class _Areas_Admin_Views_AffiliateLinks_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAffiliateLink>
    {
        public _Areas_Admin_Views_AffiliateLinks_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
  
    var isNew = Model.Id == Guid.Empty;
    ViewBag.Title = isNew ? "Добавить партнерскую ссылку" : "Редактировать партнерскую ссылку \"" + Model.Id + "\"";

            
            #line default
            #line hidden
WriteLiteral("\n\n<h2>");

            
            #line 7 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n");

            
            #line 8 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\n            <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 320), Tuple.Create("\"", 368)
            
            #line 12 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 329), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "AffiliateLinks")
            
            #line default
            #line hidden
, 329), false)
);

WriteLiteral(">\n");

WriteLiteral("                ");

            
            #line 13 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                ");

            
            #line 14 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
           Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" onclick=\"if (!confirm(\'Удалить запись?\')) { return false;}\"");

WriteLiteral(">Удалить</button>\n            </form>\n        </div>\n    </div>\n");

            
            #line 19 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 661), Tuple.Create("\"", 707)
            
            #line 21 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 670), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "AffiliateLinks")
            
            #line default
            #line hidden
, 670), false)
);

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\n\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
   Write(Html.LabelFor(x => x.ClickCost, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
   Write(Html.EditorFor(x => x.ClickCost, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 28 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.ClickCost));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
   Write(Html.LabelFor(x => x.Description, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
   Write(Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 38 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
                                                  Write(!isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Areas\Admin\Views\AffiliateLinks\Edit.cshtml"
   Write(Html.RouteLink("Назад", new { action = "Index" }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n</form>\n\n\n\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1609), Tuple.Create("\"", 1667)
, Tuple.Create(Tuple.Create("", 1615), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 1615), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1690), Tuple.Create("\"", 1760)
, Tuple.Create(Tuple.Create("", 1696), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 1696), false)
);

WriteLiteral("></script>\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1806), Tuple.Create("\"", 1851)
, Tuple.Create(Tuple.Create("", 1812), Tuple.Create<System.Object, System.Int32>(Href("~/bower_components/ckeditor/ckeditor.js")
, 1812), false)
);

WriteLiteral("></script>\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\n        if (CKEDITOR.instances[\'Description\']) {\n            CKEDITOR.remove(CK" +
"EDITOR.instances[\'Description\']);\n        }\n        CKEDITOR.replace(\'Descriptio" +
"n\', { height: 300 });\n    </script>\n");

});

        }
    }
}
#pragma warning restore 1591
