#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/AffiliateLinks/Index.cshtml")]
    public partial class _Areas_Admin_Views_AffiliateLinks_Index_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAffiliateLink[]>
    {
        public _Areas_Admin_Views_AffiliateLinks_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\AffiliateLinks\Index.cshtml"
  
    ViewBag.Title = "Партнерские ссылки";

            
            #line default
            #line hidden
WriteLiteral("\n\n<h2>");

            
            #line 6 "..\..\Areas\Admin\Views\AffiliateLinks\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\n<div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(@">
    <b>Внимание!</b> В партнерской программе учавствуют все ссылки сайта. Полный вид партнерской ссылки имеет вид: {url}/?ak={x}, где url - это абсолютный адрес страницы, а x - идентификатор партнёрской ссылки.<br />
    При переходе по партнерской ссылке идентификатор ссылки записывается в cookie браузера перешедшего пользователя и сохраняется там все время. При переходах пользователя по нескольким партнеркам все уникальные идентификаторы так же сохраняются в cookie.<br />
    Подсчет кликов с партнерской ссылки производится один раз при Sпереходе. При дальнейшей навигации по сайту учитываются только клики по баннерам, в результате чего изменяется счетчик кликов по баннерам в рамках всех партнерок, в которых учавствует пользователь.
</div>

<div");

WriteLiteral(" id=\"grid\"");

WriteLiteral(">\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Areas\Admin\Views\AffiliateLinks\Index.cshtml"
Write(Html.Partial("_GridView", Model));

            
            #line default
            #line hidden
WriteLiteral("\n</div>\n\n");

DefineSection("scripts", () => {

WriteLiteral("\n    <script>\n        $(\'#grid\').sx_gv();\n    </script>\n");

});

        }
    }
}
#pragma warning restore 1591
