#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/UserRoles/Edit.cshtml")]
    public partial class _Areas_Admin_Views_UserRoles_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMAppRole>
    {
        public _Areas_Admin_Views_UserRoles_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
  
    var isNew = string.IsNullOrEmpty(Model.Id);
    ViewBag.Title = isNew ? "Добавить роль" : "Редактировать роль \"" + Model.Name + "\"";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
 if (!isNew && User.IsInRole("architect"))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 299), Tuple.Create("\"", 342)
            
            #line 11 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 308), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "UserRoles")
            
            #line default
            #line hidden
, 308), false)
);

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 12 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
       Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" onclick=\"if (!confirm(\'Удалить запись\')) { return false;}\"");

WriteLiteral(">Удалить роль</button>\r\n            </div>\r\n        </form>\r\n    </div>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 678), Tuple.Create("\"", 719)
            
            #line 21 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 687), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "UserRoles")
            
            #line default
            #line hidden
, 687), false)
);

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 23 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
   Write(Html.LabelFor(x => x.Name, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
   Write(Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите наименование роли" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 28 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
   Write(Html.LabelFor(x => x.Description, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
   Write(Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите описание роли" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 38 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
                                                  Write(isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1571), Tuple.Create("\"", 1611)
            
            #line 39 "..\..\Areas\Admin\Views\UserRoles\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1578), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "UserRoles")
            
            #line default
            #line hidden
, 1578), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Назад</a>\r\n    </div>\r\n</form>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1701), Tuple.Create("\"", 1759)
, Tuple.Create(Tuple.Create("", 1707), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 1707), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1783), Tuple.Create("\"", 1853)
, Tuple.Create(Tuple.Create("", 1789), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 1789), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
