#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Videos/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_Videos__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMVideo[]>
    {
        public _Areas_Admin_Views_Videos__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Videos\_GridView.cshtml"
Write(Html.SxGridView(Model,
            new SxExtantions.SxGridViewSettings<SxVMVideo>
            {
                Columns = new SxExtantions.SxGridViewColumn<SxVMVideo>[]{
            new SxExtantions.SxGridViewColumn<SxVMVideo>{FieldName="Id", Caption="Внутренний идентификатор", Template=(v)=> {
                return string.Format("<b class=\"text-info\">{0}</b>", v.Id);
            }},
            new SxExtantions.SxGridViewColumn<SxVMVideo>{FieldName="VideoId", Caption="Идентификатор", Template=(v)=> {
                return string.Format("<b class=\"text-warning\">{0}</b>", v.VideoId);
            } },
            new SxExtantions.SxGridViewColumn<SxVMVideo>{FieldName="Title", Caption="Название видео"},
            new SxExtantions.SxGridViewColumn<SxVMVideo>{FieldName="SourceUrl", Caption="Источник", Template=(v)=> {
                return v.SourceUrl!=null?string.Format("<i class=\"fa fa-link\"></i>&nbsp;<a rel=\"nofollow\" href=\"{0}\">{0}</a>", v.SourceUrl):null;
            } }
        },
                EnableCreating = true,
                CreateRowUrl = Url.Action("Edit", "Videos"),
                EnableEditing = true,
                EditRowUrl = (x) => { return Url.Action("Edit", "Videos", new { id=x.Id}); },
                DataAjaxUrl = Url.Action("Index", "Videos"),
                RowCssClass = x => { return !string.IsNullOrEmpty(x.SourceUrl) ? "warning" : null; },
                ShowPagerInfo=true
            }
    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
