#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Videos/Edit.cshtml")]
    public partial class _Areas_Admin_Views_Videos_Edit_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMVideo>
    {
        public _Areas_Admin_Views_Videos_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
  
    var isNew = Model.Id == Guid.Empty;
    ViewBag.Title = isNew ? "Добавить видео сайта" : "Редактировать видео сайта \"" + Model.Title + "\"";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
 if (!isNew)
{

            
            #line default
            #line hidden
WriteLiteral("    <form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 240), Tuple.Create("\"", 280)
            
            #line 10 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 249), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "Videos")
            
            #line default
            #line hidden
, 249), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger pull-right\"");

WriteLiteral(" onclick=\"if(!confirm(\'Удалить запись?\')){return false;}\"");

WriteLiteral(">Удалить видео</button>\r\n    </form>\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<p");

WriteLiteral(" class=\"text-info\"");

WriteLiteral(">Видео обрабатывается и редактируется на основе существующего видео канала youtub" +
"e.com</p>\r\n<br />\r\n<form");

WriteLiteral(" method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 654), Tuple.Create("\"", 692)
            
            #line 18 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 663), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "Videos")
            
            #line default
            #line hidden
, 663), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.LabelFor(x => x.Title, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 24 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.EditorFor(x => x.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите название видео" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.LabelFor(x => x.VideoId, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.EditorFor(x => x.VideoId, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите идентификатор видео" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.VideoId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"alert alert-info\"");

WriteLiteral(">\r\n            Источник видео задается в случае размещения стороннего видео для с" +
"облюдения авторских прав\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.LabelFor(x => x.SourceUrl, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.EditorFor(x => x.SourceUrl, new { htmlAttributes = new { @class = "form-control", @placeholder = "Введите источник видео" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 40 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.ValidationMessageFor(x => x.SourceUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 44 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
                                                  Write(isNew ? "Добавить" : "Сохранить");

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Areas\Admin\Views\Videos\Edit.cshtml"
   Write(Html.ActionLink("Назад", "index", new { controller = "videos" }, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</form>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2149), Tuple.Create("\"", 2207)
, Tuple.Create(Tuple.Create("", 2155), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.min.js")
, 2155), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2231), Tuple.Create("\"", 2301)
, Tuple.Create(Tuple.Create("", 2237), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Admin/content/dist/js/jquery.validate.unobtrusive.min.js")
, 2237), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
