#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/_EditDate.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates__EditDate_cshtml_ : SX.WebCore.MvcWebViewPage.SxWebViewPage<DateTime>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates__EditDate_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"input-group date\"");

WriteLiteral(">\n    <input");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("id", Tuple.Create(" id=\"", 79), Tuple.Create("\"", 113)
            
            #line 4 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_EditDate.cshtml"
, Tuple.Create(Tuple.Create("", 84), Tuple.Create<System.Object, System.Int32>(Html.IdForModel().ToString()
            
            #line default
            #line hidden
, 84), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 114), Tuple.Create("\"", 152)
            
            #line 4 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_EditDate.cshtml"
, Tuple.Create(Tuple.Create("", 121), Tuple.Create<System.Object, System.Int32>(Html.NameForModel().ToString()
            
            #line default
            #line hidden
, 121), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 153), Tuple.Create("\"", 167)
            
            #line 4 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_EditDate.cshtml"
                                  , Tuple.Create(Tuple.Create("", 161), Tuple.Create<System.Object, System.Int32>(Model
            
            #line default
            #line hidden
, 161), false)
);

WriteLiteral(" type=\"datetime\"");

WriteLiteral(">\n    <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\n        <i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i>\n    </span>\n</div>");

        }
    }
}
#pragma warning restore 1591
