#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/_PicturesLookupGrid.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates__PicturesLookupGrid_cshtml_ : SX.WebCore.MvcWebViewPage.SxWebViewPage<object>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates__PicturesLookupGrid_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_PicturesLookupGrid.cshtml"
  
    var fieldName = Html.NameForModel().ToString()+"Caption";
    var pictureCaption = ViewData[fieldName];
    var prefix = (string)ViewBag.Prefix;

            
            #line default
            #line hidden
WriteLiteral("\n\n<div");

WriteAttribute("id", Tuple.Create(" id=\"", 173), Tuple.Create("\"", 196)
            
            #line 8 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_PicturesLookupGrid.cshtml"
, Tuple.Create(Tuple.Create("", 178), Tuple.Create<System.Object, System.Int32>(Html.IdForModel()
            
            #line default
            #line hidden
, 178), false)
);

WriteLiteral(">\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 223), Tuple.Create("\"", 252)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_PicturesLookupGrid.cshtml"
, Tuple.Create(Tuple.Create("", 231), Tuple.Create<System.Object, System.Int32>(Html.ValueForModel()
            
            #line default
            #line hidden
, 231), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 253), Tuple.Create("\"", 345)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_PicturesLookupGrid.cshtml"
, Tuple.Create(Tuple.Create("", 260), Tuple.Create<System.Object, System.Int32>(prefix==null?Html.IdForModel().ToString(): prefix+"."+Html.IdForModel().ToString()
            
            #line default
            #line hidden
, 260), false)
);

WriteLiteral(" />\n\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\EditorTemplates\_PicturesLookupGrid.cshtml"
Write(Html.SxGridLookup(new SxExtantions.SxGridLookupSettings
{
    DataAjaxUrl = Url.Action("FindGridview", "Pictures"),
    DefaulText = pictureCaption == null ? Html.ValueForModel().ToString() : pictureCaption.ToString(),
    Placeholder="Выберите изображение"
},
    new SxVMPicture[0]
));

            
            #line default
            #line hidden
WriteLiteral("\n</div>");

        }
    }
}
#pragma warning restore 1591
