#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/EditorTemplates/Boolean.cshtml")]
    public partial class _Areas_Admin_Views_Shared_EditorTemplates_Boolean_cshtml_ : SX.WebCore.MvcWebViewPage.SxWebViewPage<bool>
    {
        public _Areas_Admin_Views_Shared_EditorTemplates_Boolean_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\EditorTemplates\Boolean.cshtml"
Write(Html.DropDownList("", new SelectListItem[] {
    new SelectListItem() { Text = "Да", Value = "true", Selected = Model },
    new SelectListItem() { Text = "Нет", Value = "false", Selected = !Model }
}, new { @class="form-control"}));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
