#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SX.WebCore.HtmlHelpers;
    using SX.WebCore.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/VideoLinks/_GridView.cshtml")]
    public partial class _Areas_Admin_Views_VideoLinks__GridView_cshtml : SX.WebCore.MvcWebViewPage.SxWebViewPage<SxVMVideo[]>
    {
        public _Areas_Admin_Views_VideoLinks__GridView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\VideoLinks\_GridView.cshtml"
  
    int mid = ViewBag.MaterialId;
    SX.WebCore.Enums.ModelCoreType mct = ViewBag.ModelCoreType;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\VideoLinks\_GridView.cshtml"
Write(Html.SxGridView(Model,
            new SxExtantions.SxGridViewSettings<SxVMVideo>
            {
                Columns = new SxExtantions.SxGridViewColumn<SxVMVideo>[]{
                    new SxExtantions.SxGridViewColumn<SxVMVideo>{FieldName="Id", Caption="Идентификатор"},
                    new SxExtantions.SxGridViewColumn<SxVMVideo>{FieldName="Title", Caption="Название видео"},
                    new SxExtantions.SxGridViewColumn<SxVMVideo>{FieldName="VideoId", Caption="Идентификатор"}
                },
                DataAjaxUrl = Url.Action("Index", "VideoLinks", new { mid = mid, mct = mct }),
                EnableDeleting = true,
                DeleteRowUrl = x => { return Url.Action("DeleteMaterialVideo", "VideoLinks", new { mid = mid, mct = mct, vid = x.Id }); },
                EnableCreating = true,
                CreateRowUrl = "javascript:void(0)",
                ShowPagerInfo=true
            }
    ));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
